### ISSUE TITLE
Word breaks in comments

### ISSUE THREAD

**Issue by dsavenko** [hcengineering/platform#1098]
It looks awkward when the app breaks words in comments without hyphenation. Would be great to have word breaks with hyphenation according to the language rules, or just don't break words (probably also use left alignment in this case).

![image](https://user-images.githubusercontent.com/555363/156738241-2810d791-fd8c-4e98-b94c-4645fdf8238a.png)

**Comment by haiodo** [comment]
Fixed, will be in v0.6.7
