### ISSUE TITLE
HR: Create Vacancy but Last modified not updated

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#1948]
1. 
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/477235/171030716-9d957a97-8a02-4d9c-8432-48cd7bbe5725.png">

2. 
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/477235/171030761-0f2792a0-09de-4ac3-8b1e-b4fc845ce902.png">

Please check video in telegram channel

**Comment by BykhovDenis** [comment]
#1994
