### ISSUE TITLE
Update Kanban and Kanban application card to the latest design

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#251]

**Comment by MarinaMatijaca** [comment]
Kanban cards — https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=3930%3A484021
Kanban Tasks screen — https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=4353%3A469873
Kanban Candidates screen — https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=4353%3A470748
