### ISSUE TITLE
Add 'Close' button to all the creation cards

### ISSUE THREAD

**Issue by MarinaMatijaca** [hcengineering/platform#252]

**Comment by MarinaMatijaca** [comment]
Change the layout of all the cards to accommodate Close and Save buttons in the bottom.

**Comment by MarinaMatijaca** [comment]
Vacancy / Application https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=4194%3A543448
Task / Project https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=4194%3A543252

**Comment by aplatoff** [comment]
done
