### ISSUE TITLE
Remove `heft`

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#303]
* [ ] eslint - отдельно
* [ ] api-documenter - отдельно ?

**Comment by haiodo** [comment]
Adding 
```
 "skipLibCheck": true,
 "incremental": true
```
Options to tsconfog.json file in platform-rig speedup rushx build for packages/core from 10 seconds => to 3.5 seconds. Include api analysis/eslint

And provide --lite(-l) options to rush build, allow to reduce total rebuild time from 1.5 minutes to about 43 seconds :-)


So let's go with heft for now.
