### ISSUE TITLE
Comments: Copy-pasted rich text shows parse errors

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#343]
<img width="721" alt="Screen Shot 2021-11-23 at 11 15 34 AM" src="https://user-images.githubusercontent.com/87076238/143006447-515e435d-b790-413d-a031-ca2dbbc033be.png">

**Comment by omkoneva** [comment]
Не успела создать задачу - тоже хотела про это написать :) 

В тексте, который скопировала, были отступы - возможно проблема в этом. Комментарий должен был выглядеть так: 

"18/11/21 прошёл наш квиз - справился хорошо

Dmitry Savenko 1 day ago 
7.5 теория

Sergey Lunin 23 hours ago 
2 за 13"
