### ISSUE TITLE
Preferred workspace name

### ISSUE THREAD

**Issue by SahaSG552** [hcengineering/platform#3503]
warn your users about preferred workspace name, or it comes a lil bit quest =)
more than 3 symbols, only latin symbols and numbers, without special characters 

![image](https://github.com/hcengineering/anticrm/assets/15190243/6a436cca-66a8-4d18-845e-517d671848fa)
![image](https://github.com/hcengineering/anticrm/assets/15190243/7f39b76b-3bfa-4d29-94f7-a05a9ac65d52)

**Comment by haiodo** [comment]
Thanks, it is already fixed.
