### ISSUE TITLE
Добавить функцию напоминания

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#365]
Чтобы приходило уведомление на почту, когда нужно с кем-то связаться. Сейчас в trello этим довольно активно пользуемся:
![Снимок экрана 2021-11-25 в 16 02 55](https://user-images.githubusercontent.com/22656886/143411482-746667f0-da05-4b63-a888-508ef7410ac0.png)

**Comment by BykhovDenis** [comment]
#1200
