### ISSUE TITLE
Показать список только тех кандидатов, которые сейчас находятся в работе

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#371]
Как это я представляю в своей голове: 

1. Заходим в Candidates -> public и нажимаем на галочку "в работе"
2. После этого остаются кандидаты из столбцов "очередь резюме", "общаемся", "делают квиз", "технический собес", "ждём решения", "выходят", "вышли" (во всяком случае так в нашем случае с вакансией "программист")
3. Остаются только кандидаты из этих столбцов, т.е. те, по кому решения пока нет
4. Лёгким нажатием руки мы нажимаем на галочку и возвращаем всех кандидатов в общий список

Я думаю, что это будет удобно и полезно - что можно будет посмотреть в одном месте всех кандидатов, которые находятся в разработке по разным вакансиям, но понимаю, что задача возможно нетривиальная (так как названия столбцов на разных вакансиях и в разных компаниях может отличаться). Если это так, и задача нетривиальная, можно оставить её на потом

**Comment by Setepios** [comment]
А также альтернативу "тех кто не в работе" - фильтр для поиска, чтобы предлагать в выборку граждан, которые не задействованы в работе на другие вакансии в компании у этого менеджера (или у других). Чтобы не трогать тех, кем уже занимаются.

**Comment by BykhovDenis** [comment]
#1237
