### ISSUE TITLE
Remove the bottom divider from the lists

### ISSUE THREAD

**Issue by MarinaMatijaca** [hcengineering/platform#382]
Remove the divider from the bottom of all lists.
(List view, Activity, Object preview...)
![Remove divider 2](https://user-images.githubusercontent.com/22766382/143580741-8e700b55-3ada-419a-9f5b-7fc0257c8297.png)
![Remove divider](https://user-images.githubusercontent.com/22766382/143580756-4a040f34-0b3c-4fe9-bdae-6724edc0c948.png)

**Comment by aplatoff** [comment]
done
