### ISSUE TITLE
Not possible to re-order statuses for project

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#3923]
![](https://front.hc.engineering/files?workspace=platform&file=ebf6d06d-6493-4022-8849-454d640c5f21)

**Comment by haiodo** [comment]
[Bykhov Denis](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d983ba125a3831a3424ff&label=Bykhov%20Denis) why urgent?

**Comment by BykhovDenis** [comment]
Because it’s really bad not have way to change statuses order, and it not so big fix (I think about 15m-1h) (Because some status order changable, I think only for first category). Otherwise I can forget fix it

**Comment by haiodo** [comment]
😄
