### ISSUE TITLE
Unexpected internationalization error

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#3950]
![](https://front.hc.engineering/files?workspace=platform&file=aef0d967-44a1-45ed-be54-782798192dea)

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjBlNjA3MzY4ZWY5NjM0ZDNmMDMyNjgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.h4j3p_FT0jXOpvw-5l3-WMRGbWKedBBtIuVRUbza_h4">Huly&reg;: <b>UBERF-4210</b></a></sub>

**Comment by evananyonga** [comment]
When does this issue occur?

**Comment by haiodo** [comment]
I occur in experimental desktopapp, and I’ve not seen it for a while. So we could close this issue.
