### ISSUE TITLE
Enable styling popup for comment editor

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#3955]
![](https://front.hc.engineering/files?workspace=platform&file=253fd9b1-78a4-41a5-8b76-fad74d1f91d4)

is missing for comments.

We have Headings plugin enabled for comments, but icons are not shown and users can copy/paste text with headings into

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWUwYTkzMWU5ZDA1MzJmMzJjMmQ3OGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.9HKzA6dlM3lxn4xN4K1gKT_sMgInokFhEnDPg5JCFAg">UBERF-4218</a></sub>

**Comment by aonnikov** [comment]
[Sobolev Andrey](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Sobolev%20Andrey) where it does not work? I see styling popup in issue comments.

**Comment by haiodo** [comment]
I comments,
