### ISSUE TITLE
Restore Back and Close button on left part of panel

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#3977]
Close button is on right, please move it back to left and [←] button before it.

**Comment by MarinaMatijaca** [comment]
Why would we bringing the ‘Back’ and ‘Close’ button back? [Sobolev Andrey](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Sobolev%20Andrey) This is not aligned with the idea in the latest design.
