### ISSUE TITLE
Not possible to exclude inactive member in HR departament

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4142]
![](https://front.hc.engineering/files?workspace=platform&file=5a7cb795-2666-41a0-b4ca-5ea16736115a&width=50%)

**Comment by aonnikov** [comment]
[Sobolev Andrey](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Sobolev%20Andrey) so basically we need to show all active employees and currently selected employees. Can we change the popup to show objects in categories (similar to AssigneePopup), the first category we currently selected, and then all others?

**Comment by haiodo** [comment]
yes we could
