### ISSUE TITLE
Not possible to use mention toolbar button in text editor

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#4163]
Steps to reproduce:

1. Open an issue
2. Set cursor to description
3. Click Mention button in the toolbar

**Expected**: mention popup is opened and the editor is focused so I can enter some text

**Actual**: mention popup is opened but the editor is NOT focused, I cannot enter mention text. If I click on the editor to set focus, mention popup closes.

![](https://front.hc.engineering/files?workspace=platform&file=f1c13b31-36eb-429a-97e9-585301e153c6)

**Comment by the2pizza** [comment]
https://github.com/hcengineering/platform/pull/4239

Please take a look at the fix. Screen recordings are attached, feel free to feedback any notes. Thank you.
