### ISSUE TITLE
Expose connect method in the server API

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#4255]
We have `connect` method used for connecting to the server in several services. The method is almost the same. We need to get rid of duplicated code.

**Comment by FromNetToDev** [comment]
is there an API where I can read it? Any documentation on API or webhook?

**Comment by aonnikov** [comment]
@FromNetToDev , currently no, we don't have API or webhooks, but we are working on this.

**Comment by aonnikov** [comment]
Closed as not needed anymore
