### ISSUE TITLE
Ugly description changes in case of images

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4287]
![](https://front.hc.engineering/files?workspace=platform&file=feebf720-1c33-48f6-8641-263451c284af)

![](https://front.hc.engineering/files?workspace=platform&file=feebf720-1c33-48f6-8641-263451c284af)

**Comment by aonnikov** [comment]
🥲

**Comment by aonnikov** [comment]
found related problem - collaborator does not write “src” attribute to images, hence images not displayed in activity. Will be fixed in this task as well.
