### ISSUE TITLE
После удаления одного кандидата в "application" пропали все остальные

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#433]
![Снимок экрана 2021-11-30 в 15 24 59](https://user-images.githubusercontent.com/22656886/144011920-9a46ba12-d841-4d49-9a0c-95c5928722c8.png)

**Comment by aplatoff** [comment]
Это серьезная проблема -- удалили кандидата, аппликация осталась и сглючила, сделал мелкий фикс чтобы софт не падал, но надо решать по серьезному и удалять связанные объекты
