### ISSUE TITLE
При создании новой задачи в трекере удаляются все теги пользователей 

### ISSUE THREAD

**Issue by nahuka3** [hcengineering/platform#4352]
Как воспроизвести:

Tracker — New Issue — В поле description тегнуть любого сотрудника с помощью символа @  — create issue

Ожидаемый результат:

В описании задачи попадает вся добавленная информация

Фактический результат:

Теги удаляются из текста

Пример:

https://front.hc.engineering/workbench/peredelanoconf/tracker/TSK-10[](url)

<img width="1512" alt="Снимок экрана 2024-01-13 в 12 54 12" src="https://github.com/hcengineering/platform/assets/45966960/24d5f9d1-e6be-4fce-b861-678050435a66">

<img width="1512" alt="Снимок экрана 2024-01-13 в 12 53 56" src="https://github.com/hcengineering/platform/assets/45966960/9558d700-413c-404a-b85d-92be5a8034cc">

**Comment by aonnikov** [comment]
Already fixed
