### ISSUE TITLE
Inbox Fixes

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#4400]
Сгруппированный вид в Inbox выглядит довольно хреново (визуально).

![](https://front.hc.engineering/files?workspace=platform&file=08deb5b4-9b5b-4532-a3d2-a39e64fa617c)

Flat — неплохо, но он по большому счету не очень интересен.

![](https://front.hc.engineering/files?workspace=platform&file=2c53719e-d11c-42ac-b67a-12ceeafdbd28)

Что я предлагаю сделать сейчас, как временное решение:

Поскольку в сгруппированном виде, несколько событий на один объект присутствуют далеко не всегда, то в случае когда событие на объект одно — использовать то же самое представление, что и во флет.

Должно быть сделано очень быстро — иначе у меня много вопросов к реализации 😊

### Второй вопрос

Что за надпись `ToDo`, рядом с `All`? Я надеюсь что она не имеет никакого отношения к нашим тудушкам, и есть это так, то слово Todo **нельзя** использовать в любом контексте кроме наших `Todo`. Людям и так сложно объяснить что такое туду, если мы будем использовать это слово для чего-то еще другого — полный мрак

**Comment by kristina-fefelova** [comment]
[Platov Andrey](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=62c40aa9e5a6ae23d8307df0&label=Platov%20Andrey) по поводу `Todo` : да, это нашт `Todo` . Сверху это фильтры по нотификациям (по типам объектов к которым они тносятся)

**Comment by aplatoff** [comment]
Давайте уберем этот фильтр по `Todo` — надо делать либо полноценно — Applicants, Issues, Leads, Todos и т.д. либо никак. Фильтр по Todo самый бессмысленный, поскольку они и так падают в планирование

**Comment by aplatoff** [comment]
или сейчас показываются только те классы которые присутствуют в Inbox? Тогда разумно, да, давайте оставим [Fefelova Kristina](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63204fc031b9728f9e6b2e1a&label=Fefelova%20Kristina)

**Comment by haiodo** [comment]
А оно вроде бы по типам документов и показывается, вот так у меня сейчас

**Comment by aplatoff** [comment]
Cool, cool, я просто не понял как это работает 😊

**Comment by kristina-fefelova** [comment]
фильтр динамический, зависит от нотификаций в инбоксе, на скриншоте в задаче видимо только нотификация по `Todo`, поэтому только такой фильтр

**Comment by aplatoff** [comment]
И кому не лень, переименуйте тогда класс `ToDo` → `Todo`? `ToDo` не стильно 😊
