### ISSUE TITLE
Inbox Collaborators Glitch

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#4401]
Я добавил [Sobolev Andrey](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Sobolev%20Andrey) [Bykhov Denis](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d983ba125a3831a3424ff&label=Bykhov%20Denis) и [Onnikov Alexander](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=633d24fbe21d10661dbd0374&label=Onnikov%20Alexander) в коллабораторы по [UBERF-5016](https://front.hc.engineering/browse/?workspace=platform&_class=tracker%3Aclass%3AIssue&_id=65ae41d759286fc04b3931ae&label=UBERF-5016), получил следующую нотификацию в Inbox:

![](https://front.hc.engineering/files?workspace=platform&file=04e6bb68-f644-4966-a191-cdab27b1519d)

Как этот список был получен — непонятно, поскольку: [Platov Andrey](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=62c40aa9e5a6ae23d8307df0&label=Platov%20Andrey) был коллаборатором при создании. [Fefelova Kristina](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63204fc031b9728f9e6b2e1a&label=Fefelova%20Kristina) assignee при создании. Эти два человека, вообще там не должны были быть. Ну и поскольку я сам добавлял этих колобораторов, я не должен был получить в Inbox вообще ничего. Но речь сейчас не об этом а об ошибке

**Comment by kristina-fefelova** [comment]
интересно, что за изменение дискрипшина системой, когда я поменяла статус и не касалась дискрипшина (и как будто дифф слетел и меншены не выделены) 
сс [Onnikov Alexander](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=633d24fbe21d10661dbd0374&label=Onnikov%20Alexander)

**Comment by aonnikov** [comment]
“Система” наверное из Github интеграции? Мы можем получить дифф того что поменялось в дескрипшне в результате этого изменения?
