### ISSUE TITLE
Activity: Reply to Thread

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#4404]
Попытался ответить в Activity [Fefelova Kristina](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63204fc031b9728f9e6b2e1a&label=Fefelova%20Kristina)

![](https://front.hc.engineering/files?workspace=platform&file=3302cdfb-5667-4355-a4e5-9365f82bd16f)

Въехал в пень 😊 не работает.

Правильная починка займет время и до конца не очень понятна в плане навигации. Предлагаю workaround. Если чел хочет ответить в Thread — навигируем его в Chat где он сказу сможет ответить в Thread.

Тем самым у нас и фича работает, и мы знакомим пользователей с интеграцией с чатами

**Comment by kristina-fefelova** [comment]
Сделала в общем случае, как предложено выше (навигация в чат), но если мы хотим ответить из инбокса, то открываем правую панель прямо инбоксе
