### ISSUE TITLE
Default Embedded Images

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#4405]
Гайз, в коллаборативном редакторе, если я вставляю картинку, то по умолчанию ее размер должен быть 100% размера оригинала, а не 100% видимой области или еще как-то по-другому.

Сейчас картинки выглядят как угодно, но не оригинал. На самом деле это не так просто как кажется, из за всяких Retina Displays и разных dpi.

На маке сейчас у нас один браузерный пиксель — четыре физических. Сходу не помню как спросить этот коэффициент у браузера, но как то просто.

Более того, мы не знаем на каком устройстве сделана картинка и под какой dpi оптимизирована.

Предлагаю пока просто решение:

* Показывать любую картинку с коэффициентом текущего браузера, то есть если картинка размером 800×800px то мы показываем ее 400×400 для текущих Маков.
* Это даст более менее адекватное представление всех картинок среди членов команды, поскольку предполагается что команда сидит на более-менее одинаковом оборудовании

Если кто-то будет этим вопросом заниматься — расскажите сначала о планируемом решении

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWUwYTk0M2U5ZDA1MzJmMzJjMmQ4MDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.6ddSvW5Oi0nQMlK4lRcDtKiAJNGR3G08W7OgWHiCS_A">UBERF-5021</a></sub>

**Comment by aonnikov** [comment]
Можно начать с простого решения:

1. Поскольку мы не знаем источник картинки, как и кем она была сделана, можем показывать одну и ту же картинку для экранов с любой плотностью пикселей (используем атрибут [srcset](https://developer.mozilla.org/ru/docs/Web/API/HTMLImageElement/srcset) и свойство [window.devicePixelRatio](https://developer.mozilla.org/ru/docs/Web/API/Window/devicePixelRatio) для определения текущей плотности пикселей, либо используем 1x и 2x для покрытия большинства девайсов)

2. В случаях когда мы не угадали и картинка получилась слишком маленькая (или слишком большая) можно попробовать дать пользователю выбор в каком виде картинку, оригинальном или "оптимизированном"). Здесь есть нюанс - это не свойство картинки, и даже не пользовательское свойство, поскольку одну и ту же картинку пользователь может просматривать на разных экранах. Но исходя из предположения, что все члены команды используют примерно одинаковое оборудование, можно просто сохранять в картинку).

В более сложном случае можно анализировать DPI картинки. PNG может содержать метаданные ([pHYs](https://www.w3.org/TR/2003/REC-PNG-20031110/#11pHYs)), описывающие физические размеры и плотность пикселей в пикселях на метр. Например, для снимка экрана MacOS с ретина дисплеем, метаданные содержат значение эквивалентное 144 DPI). Полученное значение можно использовать для масштабирования картинки, либо просто "правильного" отображения с поправкой на плотность пикселей экрана.
