### ISSUE TITLE
Tab navigation order issue in Issue Creation popup

### ISSUE THREAD

**Issue by bogdan-ts** [hcengineering/platform#4493]
**Description:** When creating a new issue in the project's issue tracker, there is an inconsistency in the tab navigation order within the issue creation popup. After setting the Assignee, pressing the Tab key should move the focus to the next logical field, which is expected to be 'Labels'. However, the focus jumps to 'Estimation', and subsequently, it moves to 'No component'.

**Steps to Reproduce:**

1. Open the issue creation modal by clicking on 'New issue'.
2. Fill in the 'Issue title' and 'Description' fields.
3. Use the Tab key to navigate to the 'Assignee' field and set an assignee.
4. Press Tab to move to the next field.

**Expected Behavior:** The focus should move to the 'Labels' field after 'Assignee' when navigating through the fields using the Tab key.

**Actual Behavior:** The focus jumps to the 'Estimation' field, skipping the 'Labels' field, and then moves out of sequence to the 'No component' field.

![navigation1](https://github.com/hcengineering/platform/assets/6322401/1dff329a-2bf6-4e8c-b2d2-8199cdb7d4c2)

![navigation2](https://github.com/hcengineering/platform/assets/6322401/fb9ec1c1-f2e3-48c0-a8e6-c1e2791c01b4)

**Comment by bogdan-ts** [comment]
Oh, and one more thing - hitting Enter while filling out the form acts just like Tab, moving you to the next spot instead of doing what you'd expect, like saving the issue.

**Comment by aonnikov** [comment]
> Oh, and one more thing - hitting Enter while filling out the form acts just like Tab, moving you to the next spot instead of doing what you'd expect, like saving the issue.

Thanks for reporting this.
This is expected, I think it is natural to hit Enter when you edit title to go to the description, hence we applied the same logic to all fields just in sake of consistency. In most cases we have multiline editor in such forms so we can't use Enter for submitting the form. We do this by hitting Cmd-Enter (MacOS).
