### ISSUE TITLE
Update the height of top bar

### ISSUE THREAD

**Issue by MarinaMatijaca** [hcengineering/platform#463]
Update the height of top bar from 72px to 64px
FIGMA ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5125%3A566104
FIGMA ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5148%3A593727

![image](https://user-images.githubusercontent.com/22766382/144230781-d7f10a4d-80c4-42f1-b1af-691d179db2ae.png)
![image](https://user-images.githubusercontent.com/22766382/144230807-f36672fb-f87b-4b3d-a340-23d133c0d88d.png)

**Comment by aplatoff** [comment]
@MarinaMatijaca Panel top height changed to 64px, please provide example how to change view top to 64px, there are 72px in figma files everywhere.

**Comment by MarinaMatijaca** [comment]
@aplatoff Updated everywhere in figma page 'Screenshots and design'
https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5143%3A579221
