### ISSUE TITLE
"Server is under maintenance" bug found

### ISSUE THREAD

**Issue by YanaD777** [hcengineering/platform#4658]
Hi I have found a bug while trying to start the project on a Mac. The data is up to date as of February 15, 2024 22:10

http://localhost:8080/workbench/ws1

<img width="2551" src="https://github.com/hcengineering/platform/assets/54104844/61612d22-c726-410b-bb6b-2374a243c4c8" alt="Снимок экрана 2024-02-15 в 22 13 44">

http://localhost:8087/workbench/ws1

<img width="2551" src="https://github.com/hcengineering/platform/assets/54104844/4e39398a-7c25-4e5e-8888-837a625b0e0b" alt="Снимок экрана 2024-02-15 в 22 15 46">

**Comment by ThetaDR** [comment]
Hello!
Running `rushx run-local upgrade-workspace ws1` inside of `dev/tool` should resolve your issue.
`Server is under maintenance` is shown when the version of the workspace does not match the version of the server.
If you encounter any further issues during the upgrade or your problem still persists – feel free to leave another comment, I'll help with them too.
And thank you for reporting this, let's make it better together!  🙂
