### ISSUE TITLE
Google calendar connection

### ISSUE THREAD

**Issue by kulik8v** [hcengineering/platform#4710]

**Comment by kulik8v** [comment]
Проблема с подключение гугл календаря. 
Порядок действий. Нажал на кнопку "добавить". При переходе в гугловское окно показывает ошибку 403. см скриншоты

![image](https://github.com/hcengineering/platform/assets/101204005/e43be690-24be-4632-ad92-c2b4b1457146)
![image](https://github.com/hcengineering/platform/assets/101204005/24a0b941-1827-405c-b9c1-9e9b667d1d60)

**Comment by BykhovDenis** [comment]
We're currently in the testing phase of integrating with Google services, and we're actively working towards obtaining approval from Google. This involves ensuring that we meet all of Google's requirements and adhere to their policies.
