### ISSUE TITLE
Scroll is broken in chat

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4716]
![](https://front.hc.engineering/files/bb793ec1-252e-4419-8998-7f220ababdfa/ff379c91-eb23-4dff-a269-86f90c2c77f1&width=1431)

![](https://front.hc.engineering/files/bb793ec1-252e-4419-8998-7f220ababdfa/8ca70f84-b5eb-4528-8c1b-b1aae2929089&width=569)

**Comment by kristina-fefelova** [comment]
It’s too unclear how to reproduce this and what caused the error, I’m moving it to backlog until we have new details

**Comment by kristina-fefelova** [comment]
has not been reproduced in a long time, let's re-open with new details if it happens again
