### ISSUE TITLE
Failed calling rush bundle

### ISSUE THREAD

**Issue by lampart2222** [hcengineering/platform#4769]
Hi everyone.

In the last step to create the user1 user, i get an error, and can't login on workspace. i try recreate it with user2, but i cant login:

![image](https://github.com/hcengineering/platform/assets/161248245/0019532e-9201-41ae-8488-0fb2e1f137a4)

Log to create user2:

`Found configuration in /home/isaac/platform/rush.json

[1mRush Multi-Project Build Tool 5.115.0[33m[39m[22m - Node.js 20.11.1 (LTS)

> "rush bundle --to @hcengineering/tool >/dev/null && cross-env SERVER_SECRET=secret MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin MINIO_ENDPOINT=localhost MONGO_URL=mongodb://localhost:27017 TRANSACTOR_URL=ws://localhost:3333 TELEGRAM_DATABASE=telegram-service ELASTIC_URL=http://localhost:9200 REKONI_URL=http://localhost:4004 MODEL_VERSION=$(node ../../common/scripts/show_version.js) GIT_REVISION=$(git describe --all --long) node --max-old-space-size=18000 ./bundle/bundle.js create-workspace ws2 -w DevWorkspace"

tools git_version: tags/v0.6.203-0-gf2fc595ec model_version: 0.6.203 connecting to database 'mongodb://localhost:27017'... dropping database... { name: 'ws2', productId: '' } creating model... { name: 'ws2', productId: '' } 1706 model transactions inserted. creating data... ws://localhost:3333 Migrate core Migrate activity Migrate chunter Migrate calendar Migrate gmail Migrate templates Migrate telegram Migrate task Migrate attachment Migrate lead Migrate preference Migrate recruit Migrate view Migrate contact Migrate guest Migrate tags Migrate setting Migrate tracker Migrate board Migrate hr Migrate bitrix Migrate inventiry Migrate activityServer Migrate notification created indexes _migrations ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes status ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1}] created indexes _configuration ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1}] created indexes doc-index-state ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},"objectClass","attachedTo","attachedToClass","removed","stages","generationId",{"_class":1,"stages":1,"_id":1,"modifiedOn":1},{"_class":1,"_id":1,"modifiedOn":1},{"_class":1,"_id":1,"objectClass":1}] created indexes fulltext-blob ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes blob ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes transient ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes space ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1}] created indexes tx ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"objectSpace",{"createdOn":-1},{"createdOn":-1},"objectId","objectClass",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},"tx.objectId","tx._class","tx.objectClass","tx.operations.attachedTo",{"_class":1,"objectSpace":1,"_id":1,"modifiedOn":1},{"_class":1,"_id":1,"modifiedOn":1},{"createdOn":-1}] created indexes preference ["attachedTo","_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1}] created indexes activity ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass","lastReply",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},"objectId","objectClass","txId","action",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1}] created indexes attachment ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1}] created indexes guest ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes tags ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},"attachedTo","attachedToClass","tag",{"createdOn":-1}] created indexes view ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes contact ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1},{"createdOn":-1}] created indexes channel ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass","provider"] created indexes comment ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1}] created indexes chunter ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1},{"createdOn":-1}] created indexes task ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},"attachedTo","attachedToClass","status","kind",{"rank":-1},"identifier",{"createdOn":-1},{"createdOn":-1},"assignee",{"rank":-1},{"createdOn":-1},{"rank":-1},{"createdOn":-1},{"rank":-1},"priority","component","relations","milestone",{"createdOn":-1},{"rank":-1}] created indexes kanban ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes calendar ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1},{"createdOn":-1},{"createdOn":-1}] created indexes recruit ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedToClass"] created indexes setting ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1}] created indexes telegram ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1},{"createdOn":-1}] created indexes gmail ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1}] created indexes inventory ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedToClass",{"createdOn":-1},{"createdOn":-1},"attachedTo"] created indexes templates ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1}] created indexes notification ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"docNotifyContext","user","isViewed",{"createdOn":-1},{"createdOn":-1},"attachedTo","attachedToClass",{"createdOn":-1},"hidden",{"createdOn":-1},{"createdOn":-1}] created indexes hr ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},"attachedTo","attachedToClass"] created indexes tracker ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1},"attachedToClass",{"createdOn":-1},"status",{"createdOn":-1},{"createdOn":-1}] created indexes bitrix ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},{"createdOn":-1}] created indexes request ["_class","space","modifiedOn","modifiedBy","createdBy",{"createdOn":-1},"attachedTo","attachedToClass","requested","status"] create minio bucket Found configuration in /home/isaac/platform/rush.json

[1mRush Multi-Project Build Tool 5.115.0[33m[39m[22m - Node.js 20.11.1 (LTS)

> "rush bundle --to @hcengineering/tool >/dev/null && cross-env SERVER_SECRET=secret MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin MINIO_ENDPOINT=localhost MONGO_URL=mongodb://localhost:27017 TRANSACTOR_URL=ws://localhost:3333 TELEGRAM_DATABASE=telegram-service ELASTIC_URL=http://localhost:9200 REKONI_URL=http://localhost:4004 MODEL_VERSION=$(node ../../common/scripts/show_version.js) GIT_REVISION=$(git describe --all --long) node --max-old-space-size=18000 ./bundle/bundle.js create-account user2 -p 1234 -f John -l Appleseed"

tools git_version: tags/v0.6.203-0-gf2fc595ec model_version: 0.6.203 connecting to database 'mongodb://localhost:27017'... creating account John Appleseed (user2)... Found configuration in /home/isaac/platform/rush.json

[1mRush Multi-Project Build Tool 5.115.0[33m[39m[22m - Node.js 20.11.1 (LTS)

> "rush bundle --to @hcengineering/tool >/dev/null && cross-env SERVER_SECRET=secret MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin MINIO_ENDPOINT=localhost MONGO_URL=mongodb://localhost:27017 TRANSACTOR_URL=ws://localhost:3333 TELEGRAM_DATABASE=telegram-service ELASTIC_URL=http://localhost:9200 REKONI_URL=http://localhost:4004 MODEL_VERSION=$(node ../../common/scripts/show_version.js) GIT_REVISION=$(git describe --all --long) node --max-old-space-size=18000 ./bundle/bundle.js configure ws2 --list --enable *"

tools git_version: tags/v0.6.203-0-gf2fc595ec model_version: 0.6.203 {"enable":"*","disable":"","list":true} contact------------- true chunter------------- true calendar------------ false recruit------------- true telegram------------ true lead---------------- false gmail--------------- true inventory----------- false hr------------------ false tracker------------- true board--------------- false bitrix-------------- false enable [ '*' ] Enabling calendar Enabling lead Enabling inventory Enabling hr Enabling board Enabling bitrix Found configuration in /home/isaac/platform/rush.json

[1mRush Multi-Project Build Tool 5.115.0[33m[39m[22m - Node.js 20.11.1 (LTS)

> "rush bundle --to @hcengineering/tool >/dev/null && cross-env SERVER_SECRET=secret MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin MINIO_ENDPOINT=localhost MONGO_URL=mongodb://localhost:27017 TRANSACTOR_URL=ws://localhost:3333 TELEGRAM_DATABASE=telegram-service ELASTIC_URL=http://localhost:9200 REKONI_URL=http://localhost:4004 MODEL_VERSION=$(node ../../common/scripts/show_version.js) GIT_REVISION=$(git describe --all --long) node --max-old-space-size=18000 ./bundle/bundle.js assign-workspace user2 ws2"

tools git_version: tags/v0.6.203-0-gf2fc595ec model_version: 0.6.203 connecting to database 'mongodb://localhost:27017'... assigning user user2 to ws2... assigning to workspace { _id: new ObjectId('65dba89989aa2b6eea3fc452'), workspace: 'ws2', workspaceUrl: 'ws2', productId: '', version: { major: 0, minor: 6, patch: 203 }, workspaceName: 'DevWorkspace', accounts: [], disabled: false } Found configuration in /home/isaac/platform/rush.json

[1mRush Multi-Project Build Tool 5.115.0[33m[39m[22m - Node.js 20.11.1 (LTS)

> "rush bundle --to @hcengineering/tool >/dev/null && cross-env SERVER_SECRET=secret MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin MINIO_ENDPOINT=localhost MONGO_URL=mongodb://localhost:27017 TRANSACTOR_URL=ws://localhost:3333 TELEGRAM_DATABASE=telegram-service ELASTIC_URL=http://localhost:9200 REKONI_URL=http://localhost:4004 MODEL_VERSION=$(node ../../common/scripts/show_version.js) GIT_REVISION=$(git describe --all --long) node --max-old-space-size=18000 ./bundle/bundle.js confirm-email user2"

tools git_version: tags/v0.6.203-0-gf2fc595ec model_version: 0.6.203 connecting to database 'mongodb://localhost:27017'... Already confirmed:user2 `

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjU1NzNmOWQxMmEwOTk1ZmI4MzEwMzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.5e_MFJqaXIw2rt4HEnkbcXc9vEHNs8Uc-jCZGcI2xSc">Huly&reg;: <b>UBERF-5713</b></a></sub>

**Comment by haiodo** [comment]
Hi @lampart2222,

Log lines you attached are seems from running prepare.sh to execute tests.
You need to check account logs from account container, this will give more glue about what happening in your env.

To create local account please refer to readme.md, or you could do it from UI or using dev/tool CLI utility.
