### ISSUE TITLE
Добавить сортировку по дате создания 

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#478]
Вот сюда: 

![Снимок экрана 2021-12-02 в 12 26 30](https://user-images.githubusercontent.com/22656886/144363047-26ce906f-40a1-4e23-9b84-bd862a7c3e9c.png)

**Comment by aplatoff** [comment]
Можно развить тему и объяснить каким образом дата создания полезна в работе? :) Верю что полезна, просто интересен кейс в каком случае это надо. Спасибо!

**Comment by omkoneva** [comment]
Вижу три пользы: 

1. Периодически бывает, что у нас большой поток кандидатов после какого-то события - например, после дней карьеры. И к этим кандидатам мы возвращаемся спустя определённое время (в примере про дни карьеры - через несколько месяцев после мероприятия есть смысл написать некоторым из студентов ещё раз, так как когда проходят дни карьеры, у студентов учёба в разгаре, а через несколько месяцев у них как раз заканчивается сессия, и с высокой долей вероятности там есть талантливые ребята, которые будут готовы работать). Если будет сортировка по дате создания, найти всех кандидатов, с которыми мы познакомились после дней карьеры (или любого другого события) будет проще. 

2. Обычно по дате создания можно делать предположения, которые зачастую оказываются верными: если человек давно в программировании, то он может захотеть сменить сферу деятельности и уйти в менеджмент (для нас это не так актуально, но всякое бывает + для других компаний может быть актуален вопрос поиска управленца, который ранее работал программистом), с большей вероятностью он может хотеть переехать из России (если возникнет вакансия с релокейтом) и т.д. Да и в целом, по кандидатам, которые давно в базе, меньше вероятности, что они - джуны => поиск по карточкам, которые мы создали давно, может быть полезен, если нужен очень опытный специалист (хотя понятно, что стаж - это не всегда показатель квалифицированности человека). 

3. Сейчас кажется, что визуально это будет воспринимать приятней, хотя в этом пункте уверенности нет, пока не увидим как всё выглядит :)

**Comment by aplatoff** [comment]
Не хочется захламлять таблицу разными свойствами, как насчет альтернативы? Для пункта 1 не лучше ли будут теги (например тег `Дни карьеры`) чтобы можно было сразу посмотреть кандидатов с дней карьеры а не пытаться вычислить их по дате создания? :)

По второму пункту ты права, посмотреть старье -- тут без вариантов -- нужна дата создания :) Думаю сделаем :)

**Comment by omkoneva** [comment]
Про первый пункт согласна :) По поводу второго - а ты не можем сделать так, чтобы была возможность выбирать, какие колонки отображать в софте? Например, для каких-то компаний может быть неактуален город, для каких-то - отображение комментов и т.п. При этом для кого-то может быть важен источник поиска, и возможно кто-то захочет отображать его. А кто-то решит отображать только имя и должность

Или это плохое решение, чтобы компания могла самостоятельно настроить отображение конкретных колонок, которые важны/ нужны непосредственно им?

**Comment by aplatoff** [comment]
@omkoneva настраивать колонки -- это правильная идея. Будем делать
