### ISSUE TITLE
Login Failed - Unknown Error: Failed to Fetch

### ISSUE THREAD

**Issue by GeneBO98** [hcengineering/platform#4791]
I am unsure what is happening. I have tried to get this going multiple ways. I ran the scripts that were listed and still cannot log in with user1/1234. I also ran all of the commands manually, but got the same error. If I run the command to create the workspace and user manually again I can see that it fails due to the workspace and user already existing. Yet when I try to log in I just get a failed to fetch error. All of the docker containers are running.

**Comment by BykhovDenis** [comment]
Hello, apologies for the inconvenience. The issue with the docker-compose configuration containing extra parameters has been addressed. You can find the fix implemented here: [GitHub Pull Request #4798](https://github.com/hcengineering/platform/pull/4798). Thank you for bringing this to our attention. If you have any difficulties or questions, please don't hesitate to reach out for assistance.
