### ISSUE TITLE
Can't add a new member to a workspace

### ISSUE THREAD

**Issue by nahuka3** [hcengineering/platform#4810]
[When](url) I click on the name of the workspace, an error pops up

See video

https://drive.google.com/file/d/11FcNxDU6Rgiwkh_RIYzxBH0yAFnMOgWm/view?usp=sharing

**Comment by BykhovDenis** [comment]
Hello, we apologize for the inconvenience. The bug has been resolved, and you can now sign in and enjoy uninterrupted service. Thank you for your patience and understanding.
