### ISSUE TITLE
I can’t create an event in the planner

### ISSUE THREAD

**Issue by nahuka3** [hcengineering/platform#4829]
I can’t create an event in the planner

https://drive.google.com/file/d/13Ge1OlIDzbJXDtMwzbOQigi6q3pRTlR9/view?usp=sharing

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjU1NzM0MWQxMmEwOTk1ZmI4MzEwMDEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.fQk1XnP-nS12Dxak-QTi81hxSJA7ipBJ885636kTzDw">Huly&reg;: <b>UBERF-5823</b></a></sub>

**Comment by BykhovDenis** [comment]
When you enter a title and press enter, you create a todo, it appears in the unplanned (visible on the counter, you need to select this category). To create an event in the calendar, you need to enter a name at the top of the popup (“New Event” is a placeholder). Thank you for your appeal, the problems with UX are clear, we will work in this direction.

**Comment by nahuka3** [comment]
Oh shit

Thanks

**Comment by BykhovDenis** [comment]
We add autofocus for this field and rename placeholder
