### ISSUE TITLE
Empty stages are not shown in kanban and task lists

### ISSUE THREAD

**Issue by kulik8v** [hcengineering/platform#4859]
Expectation: Empty stages should be displayed so that the task can be moved to the required stage by drag and drop

![image](https://github.com/hcengineering/platform/assets/101204005/565a3cc4-abf0-4131-8171-06154049ce9b)

![image](https://github.com/hcengineering/platform/assets/101204005/545b652d-61f2-43a7-aa3c-526869512001)

It would be convenient to organise the display in such a way.

Also, as a wish - to introduce some more different options for displaying tasks: such as a gantt chart

![image](https://github.com/hcengineering/platform/assets/101204005/46780fa0-174f-4c96-bedc-77fd33c49da0)

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWUyNTg5MjMwMWI3NWQxNzFmODVmYmQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.vvuBV5G0gUGfCbZzX3zBDVbyXFdgOKubEaSnQk1jRNI">UBERF-5861</a></sub>

**Comment by BykhovDenis** [comment]
https://github.com/hcengineering/platform/pull/4861
