### ISSUE TITLE
Introduce Workspace statistics

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4878]
On creating workspace we need to store create date and same for account.

Also we need to update when uses accessed workspace, so we could track then to delete workspace.

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU2ZTEzNTk1ZmRhMGNjMDg5ODg5YjMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.sdn8Vj6fW0r-E-nVM5PdkjkNrrKZ-kqHTAOd-pw3WCg">UBERF-5882</a></sub>

**Comment by haiodo** [comment]
[Denis Bykhov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d983ba125a3831a3424ff&label=Denis%20Bykhov) I suppose you finished with this issue?

**Comment by BykhovDenis** [comment]
Yes, thank you
