### ISSUE TITLE
Candidates and vacancies / Update 'Create button'

### ISSUE THREAD

**Issue by MarinaMatijaca** [hcengineering/platform#490]
Update the button text to: 16px icon '+' and 'Name of the object'.

FIGMA ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5125%3A566104
FIGMA ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5125%3A556824

![image](https://user-images.githubusercontent.com/22766382/144394917-26fae383-40f5-471d-835b-3154652f0939.png)
![image](https://user-images.githubusercontent.com/22766382/144394942-24b99da7-d1df-4d4c-955d-46356ede9f4b.png)

**Comment by haiodo** [comment]
@SasLord Please add (+) to all Create buttons
