### ISSUE TITLE
The installation on a server via Docker Compose does not work

### ISSUE THREAD

**Issue by L4ma** [hcengineering/platform#4905]
Hello, I discovered Plane today and wanted to test it directly on my server. So I opened the documentation and wanted to run the installation. Unfortunately, an error occurs as soon as I start setup.sh and hit "Install" (see screenshot).

Can anyone help me with this or tell me what the problem is? Is something wrong in the config?

![Bildschirmfoto 2024-03-08 um 15 27 26](https://github.com/hcengineering/platform/assets/26965333/9b68c19c-7a19-4862-bce6-8243d028f3e7)

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWViMjBmYTM5ODYwOTRkMDgxY2Y3YzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.x4koJEA5DtuZiT0TVOkMq4ceQY9w490gZ7592HYkEWA">UBERF-5926</a></sub>

**Comment by aplatoff** [comment]
Won’t (can’t) fix, sorry 😊 Wrong repo, please address Plane folks @ <https://github.com/makeplane/plane>
