### ISSUE TITLE
Unable to Publish application on Public IP / Domain 

### ISSUE THREAD

**Issue by sah-anshu** [hcengineering/platform#4909]
Hi Team, I just installed using repository directly. I am trying to access from remote url but i can see endpoint is still reaching localhost:3000 How can i make it available publicly?

![image](https://github.com/hcengineering/platform/assets/9985291/972f2f1c-3eaf-4ed3-9260-bd6a226fa1b7)

Thanks in advance.

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWViYzY5NTgxN2YxMWQ2ODM3ODQ0NDMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.1SjcVANkbYT5CIKH7NuO73zyw-eazBZjyPPfWfGZT4k">UBERF-5931</a></sub>

**Comment by aplatoff** [comment]
Fixed, instructions here: <https://github.com/hcengineering/huly-selfhost>
