### ISSUE TITLE
remove debug

### ISSUE THREAD

**Issue by mingfang** [hcengineering/platform#4931]
It looks like this debug statement was meant to be deleted.

https://github.com/hcengineering/platform/blob/dd6c1d699e792df00e8fc9de910146935e794236/plugins/board-resources/src/components/KanbanView.svelte#L117

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWYwMTE0NTgxN2YxMWQ2ODM3ODRjNzciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.WB-uhsoGTwVmZ5YPnMq1Jf7KsjQsISDD97emcfuvxDI">Huly&reg;: <b>UBERF-5957</b></a></sub>

**Comment by BykhovDenis** [comment]
Hello, this plugin is outdated and should be removed, although it may not be a simple task. I would recommend against using it.

**Comment by mingfang** [comment]
That's good to know. Thanks for the heads up.
