### ISSUE TITLE
Creating tables in documents

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#4938]
### Discussed in <https://github.com/hcengineering/platform/discussions/4897>

Originally posted by **mandarinSh** March 7, 2024 Hey guys, how to add tables to documents and edit them like remove columns or so? Thanks!

Guys, it's not clear how to create tables, we need to improve it.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWYwYTRkOTgxN2YxMWQ2ODM3ODUwM2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.CclRgjbqOwWZ0tYi04DTifDvjHlTaNG7NZzXFEIKnj0">Huly&reg;: <b>UBERF-5964</b></a></sub>

**Comment by chwasifjameel** [comment]
If you have more information on this, I would like to improve it. 

Moreover, as a new user, it's not clear to me how to delete a row,column, or table.
