### ISSUE TITLE
Todos reordered on click

### ISSUE THREAD

**Issue by euaaaio** [hcengineering/platform#4985]
<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWY0M2VjNTEwZmE5NTk0M2NlZTVkODgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.8cC-bWwx0LH4APdgZkbfVmrrPmuqkvs498Ojw77KJ6c">UBERF-6036</a></sub>

**Comment by junaidNadeem** [comment]
Hi @euaaaio could you please provide a little bit more description about this bug?
