### ISSUE TITLE
Codeblock syntax highlight

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#5003]
Add syntax highlight to codeblock extension.

**Comment by junaidNadeem** [comment]
Hi, could you please provide some description of this issue?

**Comment by aonnikov** [comment]
Hi! We want code block in text editor to support syntax highlighting. Something like this: <https://tiptap.dev/docs/editor/api/nodes/code-block-lowlight>

**Comment by organic1337** [comment]
+1
would be super useful for us.

**Comment by aonnikov** [comment]
added some initial version of highlighted code blocks
