### ISSUE TITLE
Do we have bot and automation API?

### ISSUE THREAD

**Issue by alissa-tung** [hcengineering/platform#5011]
Hello, I am trying to setup a self host huly platform. Thank you for developing the software

My question is

- Do we already have bot and automation API?
- What is the license of the self host version?
- seems that `huly-selfhost-account` is running on 3000, platform web frontend is on 8087 by default, how can I configure 3000 to make CORS work correctly?

**Comment by aplatoff** [comment]
Hey @alissa-tung!

Thank you for reaching out :). To address your inquiries:

- Good timing to ask. Development of a bot API is just started and currently underway. We have significant ambitions for it and would love to share more as the feature progresses. In terms of automation capabilities, 'automation' is indeed a broad area. We have several initiatives ongoing, and we would appreciate more details about your specific use case. This way, we can determine how well it aligns with our current development efforts or if we need to make adjustments to accommodate your needs.

- The self-hosted version of Huly is released under the Eclipse Public License 2.0 (EPL-2.0). You can review the details of this license in the project repository.

- Regarding CORS configuration, you should not need to make any special modifications for it to function correctly. However, ensuring that port 3000 is accessible from outside your network is crucial. The steps to accomplish this vary depending on your setup but typically involve configuring your firewall and router settings to allow external traffic to that port.

We're here to help, so feel free to reach out if you have any more questions or need further guidance.

**Comment by alissa-tung** [comment]
> Hey @alissa-tung!
> 
> Thank you for reaching out :). To address your inquiries:
> 
> * Good timing to ask. Development of a bot API is just started and currently underway. We have significant ambitions for it and would love to share more as the feature progresses. In terms of automation capabilities, 'automation' is indeed a broad area. We have several initiatives ongoing, and we would appreciate more details about your specific use case. This way, we can determine how well it aligns with our current development efforts or if we need to make adjustments to accommodate your needs.
> * The self-hosted version of Huly is released under the Eclipse Public License 2.0 (EPL-2.0). You can review the details of this license in the project repository.
> * Regarding CORS configuration, you should not need to make any special modifications for it to function correctly. However, ensuring that port 3000 is accessible from outside your network is crucial. The steps to accomplish this vary depending on your setup but typically involve configuring your firewall and router settings to allow external traffic to that port.
> 
> We're here to help, so feel free to reach out if you have any more questions or need further guidance.

Thank you, your platform are very impressive and modern. I will consume the reply and close as complete after that
