### ISSUE TITLE
Receive 500+ type compilation errors when run in development mode.

### ISSUE THREAD

**Issue by pbxr250** [hcengineering/platform#5027]
I am running it on Linux. Production mode works without errors.

When running in dev mode: cd dev/prod rushx dev-server I get type compilation errors:

![Screenshot from 2024-03-21 09-36-50](https://github.com/hcengineering/platform/assets/26463343/c55b4ab1-17ae-4865-b308-8838a376547f)

Anyway I can close the box and continue working with the application.

I receive the same errors in vs code automatic checking:

![Screenshot from 2024-03-21 09-43-37](https://github.com/hcengineering/platform/assets/26463343/fe15ac85-3521-4aa3-8c08-1a1eaa8f27c9)

Is it the way the dev mode works right now or I am doing something wrong?

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWZiZDlhYjA5MjkyMzllMmYxOGEwM2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.5KAa-2WBSC7bYEpkt-WlsejruSVU93ckGexhMAiki8w">UBERF-6120</a></sub>

**Comment by ThetaDR** [comment]
@pbxr250 Hello! From the screenshots I'm assuming that you didn't run `rush validate`, it should fix the problem with types and make necessary `.d.ts` files. 
Were you using readme from the root of the project or from `dev` directory? The second one has old instructions and it's going to be removed.

**Comment by pbxr250** [comment]
Thanks, now d.ts files have been generated.
I have used guide from readme on the main page: https://github.com/hcengineering/platform

There is a fast start link `sh ./scripts/fast-start.sh`
Second step `sh ./scripts/build.sh` contain only this code without rush validate
```
cd ./dev/
# rush build    # Will build all the required packages.
# rush bundle   # Will prepare bundles.
rush docker:build   # Will build Docker containers for all applications in the local Docker environment.
rush docker:up # Will set up all the containers
```
So the scripts for quick start should be fixed to contain only relevant not duplicated commands:
```
sh ./scripts/presetup-rush.sh
sh ./scripts/build.sh
sh ./scripts/create-workspace.sh
```
