### ISSUE TITLE
Private project is displayed in list of all projects

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#5135]
I see a private projects that I should not have access to in list of all projects. The project is private and I’m not in the list of members. See screenshot:

![](https://front.hc.engineering/files?workspace=platform&file=3b6cc0ad-3cd7-4f83-852d-b912b6ce4735&width=1323)

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjBiYzkyY2U1MGZjYjI5NThiMDU5YzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.-yw4mO2olsg4825sf_Pl31EeSmTe21G60u7vIG9iUoA">Huly&reg;: <b>UBERF-6271</b></a></sub>

**Comment by SuneethJerri** [comment]
Hey I am new to open source, I'm interested in learning and contributing to this repository. Could I try working on this issue?

**Comment by aonnikov** [comment]
You can try if you are able to reproduce the issue, but I'm afraid, it can be a bit difficult. We have several issue marked with `good first issue` label, try to start with them first.

**Comment by SuneethJerri** [comment]
I successfully reproduced the problem and managed to hide the project names marked as private. Could you please direct me to the specific component responsible for displaying the project list?

**Comment by aonnikov** [comment]
The issue has nothing todo with any component. Visibility of objects in the platform is controlled by space security at query level. Security middleware is located here:
https://github.com/hcengineering/platform/blob/main/server/middleware/src/spaceSecurity.ts

**Comment by aonnikov** [comment]
[Denis Bykhov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d983ba125a3831a3424ff&label=Denis%20Bykhov) does guest user changes fix this problem?

**Comment by BykhovDenis** [comment]
Yes it will be fixed in Guest PR
