### ISSUE TITLE
Fix google/gmail account registration

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#5166]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjBkNjA1ZDc1NzhmZDkwY2I5ZDEwOGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.VF322S8YLSh_pvnsrWI7Cu_MrDC-kOO8uEYsVqioYQ0">Huly&reg;: <b>UBERF-6310</b></a></sub>

**Comment by aeswibon** [comment]
@haiodo Can you give more context about the issue?

**Comment by haiodo** [comment]
<https://github.com/hcengineering/platform/pull/5167>

**Comment by SuneethJerri** [comment]
is the issue resolved? if not I would like to try
