### ISSUE TITLE
Labels popup allows to add empty label

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#5176]
There is a quick label creation feature that is shown when label does not exist. It offers to create a label when no input is provided. We should not allow to add empty labels.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjBkOTNmODg1M2Y5NTk2N2JhOTU4OWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.e_bh4R0iV1GQV49MQUzJTNDuhf8JoZaLOLVo5zEc-kI">Huly&reg;: <b>UBERF-6322</b></a></sub>

**Comment by asish0512** [comment]
@aonnikov can you please assign this issue to me?
