### ISSUE TITLE
first and last name flipped

### ISSUE THREAD

**Issue by hnoh** [hcengineering/platform#5182]
After creating a user for workspace,

when avatar is clicked, first name and last name are displayed flipped.

possibly intentional; however, still weird

![image](https://github.com/hcengineering/platform/assets/104792011/246d786a-0e37-415a-8302-5234627b6651)

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjBlMzMzOTg1M2Y5NTk2N2JhOTVhZTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.Xp5zV-3vYkV8Br5LMIqa7sJwv1AGC3Tud1Ov9NmkSqI">Huly&reg;: <b>UBERF-6328</b></a></sub>

**Comment by maaz619** [comment]
<img width="583" alt="Screenshot 2024-04-04 at 16 59 09" src="https://github.com/hcengineering/platform/assets/23162832/96d214c1-b0e1-44c9-a83b-05787144d8e6">

I think it's done intentionally. The purpose is to show them flipped.

**Comment by BykhovDenis** [comment]
Hello. Are you using self-hosting solution? If yes, you can just remove or change LAST_NAME_FIRST in environment
