### ISSUE TITLE
Добавить возможность изменить порядок вакансии

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#519]
Создала вакансию "инженер-программист", так как в вакансии "программист" сломалась доска. Вакансия "офис-менеджер" тоже менее актуальная, поэтому было бы удобней, чтобы вакансия "инженер-программист" была в списке первая, "офис-менеджер" вторая, а "программист" вообще ушла в архив, например. Но сейчас поменять порядок вакансий и расставить их по приоритетам нельзя: 

![Снимок экрана 2021-12-03 в 17 38 41](https://user-images.githubusercontent.com/22656886/144589101-6ae1673e-81cd-4e29-8919-6b648c2def95.png)

**Comment by aplatoff** [comment]
Will do sorting instead, #641
