### ISSUE TITLE
Undefined class label in Class Settings for parent type "Project"

### ISSUE THREAD

**Issue by m2jobe** [hcengineering/platform#5217]
**Update**
Looks like the Project type Model is missing UX properties.

To fix this we need to add the following UX Property in line 184 after creating our Project Model:

```
@Model(task.class.Project, core.class.TypedSpace)
@UX(task.string.ProjectName, task.icon.Task, task.string.ProjectName)
```

Here we are setting the label to ProjectName ("Project") and temporarily setting the icon to task, we need to introduce a Project Icon or use an alternative icon that is appropriate.

**Description:** 

In Class Settings, the parent class Project does not have its label attribute set, as seen in the screenshot below it is returning undefined. Project is the parent class for Vacancy, Funnel, Project and Board. To prevent confusion for users we should fix to ensure the class type has a label

**Environment:**

This was replicable in both production and local environments

Issue:
<img width="1680" alt="Screen Shot 2024-04-05 at 5 40 08 PM" src="https://github.com/hcengineering/platform/assets/9561974/fe2a64c5-f987-4b99-9c68-7423a7462bb1">

Fixed: 
<img width="1670" alt="Screen Shot 2024-04-05 at 6 46 12 PM" src="https://github.com/hcengineering/platform/assets/9561974/925138c8-8c00-4b8f-ae1a-421c74cf4ccf">

**Potential Fix:**

Update the creation of the Project type in models->task->src->index.ts to ensure it returns a label

This is consumed by ClassHeirarchy.svelte. **clazz.label** is undefined in the case of the Project class it currently has no labvel attribute

```
{#each classes as cl}
  {@const clazz = client.getHierarchy().getClass(cl)}

  {@const desc = getDescendants(cl)}
  <NavItem
    label={clazz.label}
    isFold
    empty
    {level}
    selected={cl === _class}
    on:click={() => {
      console.log("cl", cl, clazz)
      dispatch('select', cl)
    }}
    on:contextmenu={(evt) => {
      showMenu(evt, { object: clazz })
    }}
  />
  {#if desc.length}
    <svelte:self classes={desc} {_class} level={level + 1} on:select />
  {/if}
```

**Comment by aplatoff** [comment]
I've no idea what this is about

**Comment by zanderisrael** [comment]
im seeing this too, might want to reopen, on v0.6.377
