### ISSUE TITLE
Role assignment editor should allow to select from space members

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#5272]
When assigning users to space roles, the editor allows to select all users from the system. In some cases (or always?) we want to select users from the list of space members only.

In this task we need to implement custom editor for role assignment that will allow to filter out non space members.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjE1NTRkNzI0N2IzZDJhZDI5MjJkZTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.SOu3cTYaQrTqwA8dbflkXYCHu1ZLxO1y6yfWCu8a7Dk">Huly&reg;: <b>UBERF-6454</b></a></sub>

**Comment by lexiv0re** [comment]
[Alexander Onnikov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=633d24fbe21d10661dbd0374&label=Alexander%20Onnikov) actually, to my surprise it’s been already implemented (<https://github.com/hcengineering/platform/blob/main/plugins/setting-resources/src/components/typeEditors/RoleAssignmentEditor.svelte>) 😊 It will limit the assignment selection to the members if it’s a private space.
Please let me know if it works for your case.

**Comment by aonnikov** [comment]
Mark it as resolved, then !
