### ISSUE TITLE
(Bug) => last name value should be empty instead of "null"

### ISSUE THREAD

**Issue by thomas-x-69** [hcengineering/platform#5290]
I logged in as: "Thomas Ashraf" but when I opened the app my name was: first name = "Thomas Ashraf" last name = "Null" like this:

![image](https://github.com/hcengineering/platform/assets/66570810/60b4d3f7-1f0d-4283-8e01-fdeda343a2fa)

please solve this naming bug

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjE2NzdlMTYyMTNkMWYyYWE4YTE4ZTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.CyxjOQT3FXSLAV42upIaMjgf-IBZMW-VV8TE3CO8Ghw">Huly&reg;: <b>UBERF-6475</b></a></sub>

**Comment by praveen-erramilli** [comment]
I found this bug during signup with Google profile. I fixed it in https://github.com/hcengineering/platform/pull/5328
But existing users need to rename their profile under settings
