### ISSUE TITLE
(Bug) => Mark All as read button is not working

### ISSUE THREAD

**Issue by thomas-x-69** [hcengineering/platform#5293]
in the inbox: when I click mark all as read, It is not working.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjE2N2E3MjYyMTNkMWYyYWE4YTE5OTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.2nLInzAGjZS58Ks-_HY5CTLVEdaDVFE_GAcInFPGVsg">Huly&reg;: <b>UBERF-6478</b></a></sub>

**Comment by aonnikov** [comment]
@thomas-x-69 thanks for reporting this. I was not able to reproduce this, though. Could you attach video or steps to reproduce the issue.

**Comment by thomas-x-69** [comment]
I tried to click it on my account multiple times, but nothing changed. so I read it manually.

to record a video of the problem I created another account and tried it again

I don't know if it is clear in the video or not but I clicked about 5 times to get a response

https://github.com/hcengineering/platform/assets/66570810/27604260-cf39-4710-9bad-aedc22ff5cd3

(it's better than the first attempt but still have an issue)

@aonnikov

**Comment by aonnikov** [comment]
@thomas-x-69 
Thanks for your efforts for reproducing the issue and recording the video.

Probably it is not very intuitive, but it works as expected. Unread status is displayed as red marker on the top left corner. By default the inbox shows both red and unread messages. To completely remove notifications from inbox, click the dropdown button and select Archive All option.

**Comment by thomas-x-69** [comment]
thanks for your clarification
