### ISSUE TITLE
office -> change "finalize editing" button

### ISSUE THREAD

**Issue by thomas-x-69** [hcengineering/platform#5294]
after finishing it's much better for UX to make the button text = "Done" with a highlight colour (orange) for more readability and to avoid confusion like this:

![image](https://github.com/hcengineering/platform/assets/66570810/b060ff8d-c91b-4d8d-85f2-9b5415568273)

instead of this:

![image](https://github.com/hcengineering/platform/assets/66570810/e3c702e5-2cf8-457c-bc59-e47848ed2932)

( at least the colour should be changed )

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjE2N2NiZTYyMTNkMWYyYWE4YTE5Y2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.6cyWNXS0HBh5SswYbG79aIpBdJzLXIsnHv4Dn039FvY">Huly&reg;: <b>UBERF-6480</b></a></sub>

**Comment by ashleshshenoy** [comment]
can i work on this ?
