### ISSUE TITLE
Feature Request: Lock document content

### ISSUE THREAD

**Issue by jrzwee** [hcengineering/platform#5299]
### Description of the issue

The ability for locking content is a safe way protecting unintentional edits.

The process of ODOO 17:

![image](https://github.com/hcengineering/platform/assets/10603792/ce2072d2-f1e8-4792-8e4e-6de9958e99e6)

**Comment by aplatoff** [comment]
This is nice idea, thank you!

What do you think about to align it with versioning? 

Internally we have history of every document, but UI to work with the history is not clear. Users may have some versions in mind, but we would not like to introduce complex UI to manage document versions. One of things we can do based on this "Lock Content" idea, is automatic generation of next version each time anybody lock content of a document.

**Comment by jrzwee** [comment]
I have also created https://github.com/hcengineering/platform/issues/5270 there are of some similarities to this one.

Let's have a look how other tools solve this issue:
- ODOO17 document behaviour is similar to Huly. One can edit documents directly if they are not locked.
- BookStackApp is in read only in general and one need to select "edit" for changing the document. Each time a document is edited, a new version for the history is created.
- Notion also has a "lock" page feature. The version history is not bound to it.
- Anytype also has a "lock" page feature. The version history is not bound to it.

I think the locking of documents does not need to bound to versioning. I would keep them seperated.
