### ISSUE TITLE
Popups in the project allow to add empty ones

### ISSUE THREAD

**Issue by asish0512** [hcengineering/platform#5350]
Users should not be able to create empty ones.  I am listing one here.

https://github.com/hcengineering/platform/assets/14013271/6b455176-eb7b-4798-9cc1-11bf3196c792

Issue similar to #5176

**Comment by Ponnada96** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by asish0512** [comment]
@Ponnada96 I have raised the PR for this.
