### ISSUE TITLE
Wrong status colors

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#5407]
![](https://front.hc.engineering/files?workspace=platform&file=820c3411-4150-4b5d-adf1-ac2fbd60dfac&width=1393)Please check on issue <https://front.hc.engineering/workbench/platform/tracker/UBERF-6228>

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjIyMGViMDEyMTRhOWI4YTEyZTRiN2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.deWb8qgmhVajGhhVR5hcP2YNJ63M12aDogvDPvJWNRE">Huly&reg;: <b>UBERF-6638</b></a></sub>

**Comment by ThetaDR** [comment]
Happens when opened from `All Issues` (info to reproduce it)
