### ISSUE TITLE
development mode is not working

### ISSUE THREAD

**Issue by thomas-x-69** [hcengineering/platform#5462]
in the development mode when opening the Workspace it shows a loading icon endlessly
like this:

![image](https://github.com/hcengineering/platform/assets/66570810/d02c2c82-308a-4b05-baf6-da09394933a7)

and gives these errors in the console:

![image](https://github.com/hcengineering/platform/assets/66570810/bceaf692-ccfb-4e1c-aaf3-7f81b7798340)

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjI5NTBmMGY2ZjRiZWI4MjliNWExYTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.nF7ggKYO401AogAbOk1Slr6mxn0CmC-cFzuyr3xrvko">Huly&reg;: <b>UBERF-6721</b></a></sub>

**Comment by Jberma23** [comment]
yeah having the same issue the instructions aren't clear

**Comment by thomas-x-69** [comment]
I can't run the project. Does anyone have ideas?
@haiodo

**Comment by thomas-x-69** [comment]
> yeah having the same issue the instructions aren't clear

@Jberma23 
any ideas?

**Comment by BykhovDenis** [comment]
Please build and run docker....
