### ISSUE TITLE
Cloud terms & pricing

### ISSUE THREAD

**Issue by chupzzz** [hcengineering/platform#5490]
### Description of the issue
At first, thanks for your amazing product! Was using it few weeks as a personal task tracker and more than happy with it.
Now I'm thinking to move my small team to your solution but I'm a bit confused: there's no mention of price at all! Nor that it's free, nor that it's paid or _will be_ paid. We can't decide if we don't know the rules.

Please, clarify usage terms for your cloud solution.

_Yes, I know we can self-host it, but we're small team and cloud will be enough for us for some time._

Thank you for great product!

**Comment by aplatoff** [comment]
Hi @chupzzz! 

Thank you very much for your kind words about the product. We will certainly add a section on cloud pricing soon. However, our core principle remains unchanged: everything at cloud Huly will be free forever. 

We will, however, charge for resources, primarily storage, AI, and bandwidth (HD video conferencing). I'm also confident that Huly will be more affordable than the alternatives, barring some extreme resource usage scenarios.

**Comment by chupzzz** [comment]
Thanks for update! So we're jump in 👌

**Comment by aplatoff** [comment]
Welcome aboard! Please don't hesitate to report any problems or request any improvements/change.
