### ISSUE TITLE
[Bug] Invite for participants in Planner not working?

### ISSUE THREAD

**Issue by jrzwee** [hcengineering/platform#5510]
# Description of the issue

The invitation for participants in the Planner tab does not seem to work properly.

# Your environment

* Version of huly: Current
* Browser: Edge Version 124.0.2478.67 (Offizielles Build) (64-Bit)
* Your operating system:
  ![image](https://github.com/hcengineering/platform/assets/10603792/d4064713-7601-46b3-bd0f-68da823acbe6)

# Expected behaviour

When I invite a participant to a meeting, they should see it in their calendar.
![image](https://github.com/hcengineering/platform/assets/10603792/e7e8431e-028e-4c0a-95de-0efc3f792903)

# Actual behaviour

No notification is shown, no calendar entry for the other person.

**Comment by BykhovDenis** [comment]
Fixed
