### ISSUE TITLE
Плагин сохраняет резюме в первую борду в Candidates

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#555]
1. Заходим в ld или hh
2. Выбираем кандидата 
3. Нажимаем на плагин
4. Выбираем нужную борду
![Снимок экрана 2021-12-07 в 14 50 07](https://user-images.githubusercontent.com/22656886/144988543-18ea807b-bb89-4d61-aaaa-5da714eccdc6.png)
5. Import 
6. Кандидат отображается в первой борде из списка Candidates, а не в ту, которую выбрали мы, и которая нужна нам
![Снимок экрана 2021-12-07 в 14 50 47](https://user-images.githubusercontent.com/22656886/144988576-8f31274e-b4fa-4a15-b2c3-eb3f8ed64498.png)
![Снимок экрана 2021-12-07 в 14 50 57](https://user-images.githubusercontent.com/22656886/144988594-b1c04122-4e85-4782-9896-26c140dad5e0.png)
______________

Также будет удобно, если можно будет по умолчанию выбирать борду, которая нам в данный момент наболее интересна и наиболее актуальна для нас.

**Comment by BykhovDenis** [comment]
https://github.com/hcengineering/linkedin-chrome/pull/5
