### ISSUE TITLE
Добавить возможность пролистывания статустов в вакансии курсивом

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#571]
Сейчас курсивом пролистнуть список статусов не получается, поэтому на ноутбуке (или любом небольшом экране) не видно, получилось у меня создать новый статус или нет (чтобы это понять, нужно уменьшать шрифт на всём экране, но если статусов будет сильно больше, это не поможет + это не сильно удобно): 

![Снимок экрана 2021-12-08 в 12 45 20](https://user-images.githubusercontent.com/22656886/145155136-2b1640c2-b126-4244-b3ca-aea52fd3bbd6.png)

**Comment by aplatoff** [comment]
Не совсем понятна проблема, Оля можешь проверить починено ли это?

**Comment by omkoneva** [comment]
Проверила - починено :) Спасибо!
