### ISSUE TITLE
Добавить возможность создавать новый статус в вакансии через кнопку "add new column"

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#572]
![Снимок экрана 2021-12-08 в 12 49 22](https://user-images.githubusercontent.com/22656886/145155561-10da2847-9ef3-4c29-b5d3-dd543673da62.png)

**Comment by omkoneva** [comment]
Сейчас это не самая острая необходимость, но так будет просто удобней работать (как альтернативный способ создания статусов) и ускорит работу менеджера

**Comment by aplatoff** [comment]
кнопку пока убрали
