### ISSUE TITLE
French Language

### ISSUE THREAD

**Issue by naif0s** [hcengineering/platform#5769]
### Description of the issue
How can I contribute to the project by adding the French language?

**Comment by lexiv0re** [comment]
Hi @naif0s, it would be really great to add French language support. 
One can find all the translations in `lang` folders across the repo. They contain separate files with translations for different languages. The following PRs can be used as an example of adding new translations (they might not contain all the necessary folders to update though): https://github.com/hcengineering/platform/pulls?q=is%3Apr+is%3Amerged+spanish

**Comment by ygranger-oa** [comment]
Hi,

@naif0s if you need help...

**Comment by naif0s** [comment]
Hi, @ygranger-oa 

I've started translating a few files, how do you want to proceed?

**Comment by ygranger-oa** [comment]
I can check your commits before your pull request.

**Comment by dingdayu** [comment]
Hi, @ygranger-oa @lexiv0re   I also want to help provide Chinese language pack.

I found the following three language packages in the project. Can you introduce them?

- packages/ui/lang/en.json
- packages/core/lang/en.json
- server/account/lang/en.json

Via https://github.com/hcengineering/platform/pull/4788/files I noticed that plugins have different language packages. Do I need to translate them separately? 

If there is bootstrapping documentation, that would be great. If not, I'd like to start with what the UI can see, and then provide translations for Plugins.

**Comment by lexiv0re** [comment]
Hello @dingdayu, adding Chinese language support would be really great as well! If you intend to work on that, could you please create a separate GitHub issue to keep this one focused on discussions about French language support? Thanks!

To add full support all packages and plugins need to be translated. Plugins form UI as well as packages so you won't see any real difference between them from the translation point of view.

You are right that to get the full list of files one can search for `en.json` files. E.g.:
<img width="719" alt="image" src="https://github.com/hcengineering/platform/assets/20221821/5a9845e6-38a0-4bcd-9267-bc6867f08089">

As for the documentation, at the moment there's not much more than in the main readme file.
