### ISSUE TITLE
Cannot connect to Google Calendar

### ISSUE THREAD

**Issue by hkjens** [hcengineering/platform#5778]
### Connect Google Calendar account fails
Nothing happens after clicking the **Connect** button in **Settings > Integrations > Calendar > Add**

### Your environment
* Huly 0.6.250
* DuckDuckGo and also in Chrome
* MacOS

### Steps to reproduce
Go to **Settings > Integrations > Calendar > Add** and click on **Connect**

### Expected behaviour
I expect some kind of connect popup

### Actual behaviour
![Huly Calendar Connect fails](https://github.com/hcengineering/platform/assets/63708149/b4e6ed03-ae2e-4e3e-b133-8b6c5af7529f)

**Comment by BykhovDenis** [comment]
Fixed. Thank you for your report
