### ISSUE TITLE
[Chat] Cannot select text from code block

### ISSUE THREAD

**Issue by kristina-fefelova** [hcengineering/platform#5787]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjY5NTZiNDg3MjUzZDAzOGViYTBkZTQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.3MZnSCVx_N2LvWHZRUggIl35ya8GhPcfZ0DuXP_iT6k">Huly&reg;: <b>UBERF-7235</b></a></sub>

**Comment by Juniorjes21** [comment]
Hola
