### ISSUE TITLE
[UI bug] floating toolbar blocks link dialog

### ISSUE THREAD

**Issue by AbigailDawson** [hcengineering/platform#5839]
When highlighting text and clicking the link icon to add a link, the floating toolbar remains overlayed above the dialog, blocking it in some positions (see screenshot). Feel free to reassign if needed.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjcwNDMyODQ0NjVhYzg4MTBhNzBkNWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.WFLZodB_Qpigt6tHJfHEGgpmlkHEks6l07aA9xn_bRc">Huly&reg;: <b>UBERF-7301</b></a></sub>

**Comment by aonnikov** [comment]
The problem is that the editor uses different library for showing popups, we need to get rid of it and until then similar problems will occur.

**Comment by aonnikov** [comment]
This should be fixed now, the toolbar should disappear when a link popup is opened.

**Comment by AbigailDawson** [comment]
test

**Comment by AbigailDawson** [comment]
test
