### ISSUE TITLE
Add Chinese Language

### ISSUE THREAD

**Issue by dingdayu** [hcengineering/platform#5856]
### Description of the issue

Add Chinese support to UI.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjcyNjdiODg1M2Q4NDkxODJiN2NhNzUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.Lxv8wfKioCiQmdGlp_FqW0jlpnCOUM98KEb4LrNhZiw">Huly&reg;: <b>UBERF-7321</b></a></sub>

**Comment by dingdayu** [comment]
Link to: https://github.com/hcengineering/platform/issues/5769

**Comment by dingdayu** [comment]
PR Link to: https://github.com/hcengineering/platform/pull/5859

Pls @lexiv0re reveiw.

**Comment by dingdayu** [comment]
Hi @haiodo I see [PR](https://github.com/hcengineering/platform/pull/5859) has been merged, and you have also increased [select commit](https://github.com/hcengineering/platform/commit/1c8bdb81f7be2f06ee3c9ced019b9091661588eb), but I at the [official website(https://huly.io/)](https://huly.io/) did not see the option for Chinese, my account is: 614422099@qq.com, you can share the official website deployment cycle?

I've tried refreshing the browser cache.

![CleanShot 2024-06-21 at 11 21 45@2x](https://github.com/hcengineering/platform/assets/2040348/3833290f-205f-4d44-92b3-c68e09da9d1a)

**Comment by aplatoff** [comment]
Hi @dingdayu, 

Thank you very much for your great contribution! 

Projects like Huly never deploy committed code directly to production servers and usually it pass several stages of testing and verification. Also there is no "schedule". Internally we committed to have Huly.io updates at least every two weeks (as bare minimum). In reality we update Huly more often, can be a few times per week. 

As for your great contribution, you may expect Chinese language on Huly.io in a few hours, by noon CET timezone.

Thank you!
