### ISSUE TITLE
Google Calendar Integration - Event Duplication

### ISSUE THREAD

**Issue by FizzBuzz791** [hcengineering/platform#5867]
### Description of the issue
According to the title, events synced from Google Calendar seem duplicated. 

### Your environment
* Version of huly: Web? Not sure where I find this... I'm using huly.app
* Browser (and version): Edge 127.0.2638.2 (Official build) stable app, dev channel (64-bit)
* Your operating system (and version): Windows 11

### Steps to reproduce
1. Connect to Google Calendar.
2. Go to the Planner tab and observe incorrect entries.

### Expected behaviour
Planner looks the same as Google Calendar.

### Actual behaviour
Huly Planner
![image](https://github.com/hcengineering/platform/assets/2747764/59c22f3e-1ae7-4fad-9137-103d5a6b62fd)
Google Calendar
![image](https://github.com/hcengineering/platform/assets/2747764/ea4ca8aa-784b-4c2a-9567-c0d4ef74557d)

The "Kathys Birthday" entry on Friday 21st is the only correct entry.

### Possible solutions
It could be an issue with the date being passed but not the year.

**Comment by BykhovDenis** [comment]
Hello. Could you please provide your workspace name and your account email? Thank you

**Comment by BykhovDenis** [comment]
Thank you for your feedback. The issues will be resolved in the next version.

**Comment by FizzBuzz791** [comment]
Awesome! Do you still need the workspace name and email?

**Comment by BykhovDenis** [comment]
No, thank you, I've found it in your GitHub account). It should be fine now. Let me know if something wrong.
