### ISSUE TITLE
Manage statuses / Local UI 

### ISSUE THREAD

**Issue by MarinaMatijaca** [hcengineering/platform#591]
Update the UI for Managing statuses from the Recruitment application.
Navigation: Recruitment > Vacancy > Manage statuses

FIGMA screen ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5349%3A619599
FIGMA screen ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5315%3A610420

![image](https://user-images.githubusercontent.com/22766382/145235356-5ae7c55e-6cff-4a25-8c2b-54805e152749.png)

**Comment by aplatoff** [comment]
We can't change template after Vacancy/Project created. Can we please stay with current UI for managing statuses, and add `Template` parameter to Vacancy/Project creation dialog? So user can choose template at creation point. After Vacancy/Project created user can customize statues specific to this vacancy as it is now.
