### ISSUE TITLE
Internationalizations on notification

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#5915]
![](https://front.hc.engineering/files?workspace=platform&file=afd33ba2-3824-4c40-9e0e-0773af47be34&width=512)

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdhNGZiZjNlOGFhOTFjZTY2YWVkMmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.GEq46maabCFYg-Gu7z5JilgT0be9nn-cwlrrDUws7DA">Huly&reg;: <b>UBERF-7396</b></a></sub>

**Comment by kristina-fefelova** [comment]
Should be fine now, lets reopen if it appears again
