### ISSUE TITLE
Adding multiple Todo items when spamming enter

### ISSUE THREAD

**Issue by xxxoooxoxo** [hcengineering/platform#5937]
### Description of the issue
If submitting mulitple times before server responds, there can be multiple todo items added to your list

### Your environment
Latest Cloud (Server version 0.6.256 0.6.256)
Chromium && Safari

### Steps to reproduce
Create a new todo item and submit it multiple times before UI updates

### Expected behaviour
Should only update once, and not allow multiple submissions until the server responds

### Actual behaviour
Submits multiple times

### Possible solutions
1. Disable submits until the server responds 
2. Upon immediate submission, clear input field

**Comment by Nishant-FactWise** [comment]
Hey could i take up on this issue

**Comment by shivang2000** [comment]
hey could i take up on this issues
