### ISSUE TITLE
Issue with email links in text editor

### ISSUE THREAD

**Issue by lexiv0re** [hcengineering/platform#5965]
When one types an email in a text editor it creates a `mailto` link but it continues to mark it as a link even if you type `,` after that. E.g. `test@hello.com,somethingelse`

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjgyNjcwOTc0ZmRjOGExYzc1OGE5MjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.nEdhE_NZAtPOp2T12M_CG7z5w7jWt63XSHMRh162Bvc">Huly&reg;: <b>UBERF-7462</b></a></sub>

**Comment by aonnikov** [comment]
we can try to use `validate` method to exclude invalid links:

<https://tiptap.dev/docs/editor/extensions/marks/link#validate>
