### ISSUE TITLE
Изменить очерёдность кандидатов с вакансиях от первого добавленного к последнему

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#598]
Вверху списка отображать тех, кого добавили недавно, либо в чью карточку внесли последние изменения, а не наоборот:

![Снимок экрана 2021-12-09 в 11 53 04](https://user-images.githubusercontent.com/22656886/145336727-09c7252b-e2e6-4647-b798-1ff2c4389a9b.png)

**Comment by aplatoff** [comment]
done
