### ISSUE TITLE
virtual office Video conference on self hosted version

### ISSUE THREAD

**Issue by mindmatter-ai** [hcengineering/platform#5991]
### Description of the issue
as a user when i enter the virtual i am not able to start a video conference with the team 
### Your environment
* Version of huly Latest self hosted
* Browser (and version) Chrome
* Your operating system (and version) Mac
* 

### Steps to reproduce
click on virtual office on the left 
click on the video conference room to start a video 

### Expected behaviour
start a video similar to the cloud based 
### Actual behaviour
i get service not configured 
### Possible solutions
(Not obligatory)
i am not able to find the solution in the documentation

**Comment by Sanjaikabilan** [comment]
Same issue here,
Solution would be appreciated

**Comment by BykhovDenis** [comment]
Virtual office and 3rd-party integrations not supported for self-hosting
