### ISSUE TITLE
Tooltip without background issue

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#601]
Sometimes there is no background for tooltips.

Google Chrome:

![Screenshot 2021-12-09 at 17 11 36](https://user-images.githubusercontent.com/477235/145377059-29fed600-e6ed-43a2-8a72-28cbe234e8af.png)

![Screenshot 2021-12-09 at 17 13 41](https://user-images.githubusercontent.com/477235/145377272-4f087ac7-109e-4606-af40-542a13b38640.png)

**Comment by aplatoff** [comment]
done
