### ISSUE TITLE
Cannot delete the custom field

### ISSUE THREAD

**Issue by MFYDev** [hcengineering/platform#6056]
You cannot delete the custom field through this button

![iShot_2024-07-11_13 50 20](https://github.com/hcengineering/platform/assets/53750381/eae0b3ae-ad85-4338-bcbf-bbac90465e08)

**Comment by BykhovDenis** [comment]
Hello. Thank you. Already fixed, https://github.com/hcengineering/platform/pull/6054, will be implemented in the next version.
