### ISSUE TITLE
Desktop progress is not shown during upgrade

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6189]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmE5MGVlYWRhNTY1NDI5ZDY2MjVjYTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.dvNTpwIaRMUJDe0NAy8asOg6yp6HWV7dRhROxt6T8NI">Huly&reg;: <b>UBERF-7738</b></a></sub>

**Comment by lexiv0re** [comment]
Not reproducible for me. If it reproduces for you again please provide more details:

1. Screenshot during the update download
2. If there are any clues in the dev tools console
3. Your exact case e.g. if the app is open when the update is published or not
4. `tail -n 2000` of the logs file
