### ISSUE TITLE
Get rid of productId in workspace Id

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#6192]
not needed anymore

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmE5MTgyYmRhNTY1NDI5ZDY2MjVjZmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.E3-R6V4lfBsmR6T9BTNc8DVb5xEzC7JecY9nHDWAhMk">Huly&reg;: <b>UBERF-7741</b></a></sub>

**Comment by lexiv0re** [comment]
Actually, we should get rid of productId everywhere.

**Comment by aonnikov** [comment]
[Alexey Zinovyev](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63fefffb6e876eaf328df878&label=Alexey%20Zinovyev) do we still need this issue?

**Comment by lexiv0re** [comment]
[Alexander Onnikov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=633d24fbe21d10661dbd0374&label=Alexander%20Onnikov)nope, it’s already done.
