### ISSUE TITLE
Create a way to Archive vacancies

### ISSUE THREAD

**Issue by MarinaMatijaca** [hcengineering/platform#622]
FIGMA Archive vacancy ➡️  https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5360%3A646644
FIGMA List of archived vacancies ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5427%3A382170
FIGMA List of applications within archived vacancy ➡️ https://www.figma.com/file/Iy9NTowbY13aCuryyk9SqB/Platform?node-id=5427%3A384206

![image](https://user-images.githubusercontent.com/22766382/145976293-19cdc661-70cb-468a-80bf-39e2a1c73ed3.png)

![image](https://user-images.githubusercontent.com/22766382/145974183-b09b2334-e52f-4129-a89e-b9c3bef73438.png)

**Comment by aplatoff** [comment]
This is UI links for duplicate issue #574
