### ISSUE TITLE
Can't create issue on template project

### ISSUE THREAD

**Issue by chekoopa** [hcengineering/platform#6229]
### Description of the issue

When creating an issue in "Welcome to Huly!" with a priority and assignee, after pressing "Create issue" it hangs.

### Your environment

* huly.app, particularly: huly 0.6.270, model version 0.6.266
* Chromium 120.0.6099.71
* NixOS 23.11.20231212.cf28ee2

### Steps to reproduce

Create a new workspace, then create an issue in the tracker (intentionally skipping HULY-2).

### Expected behaviour

A new issue appears.

### Actual behaviour

It hangs perpetually and shows an error in the console:

```
severity: "ERROR"
code: "platform:status:UnknownError"
params.message: "Plan executor error during findAndModify :: caused by :: Cannot apply $inc to a value of non-numeric type. {_id: "tracker:project:DefaultProject"} has the field 'sequence' of non-numeric type null"
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmFjNzBhNWRhNTY1NDI5ZDY2MjY5MTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.WvErRi4XT8vS7DLAbJDNOE9crAzUEKGkXWoQOokJcTk">Huly&reg;: <b>UBERF-7780</b></a></sub>

**Comment by BykhovDenis** [comment]
Hello. Did you try it on huly.app or on self-hosting?

**Comment by chekoopa** [comment]
Hi. It was on huly.app, I'll edit the post accordingly.

**Comment by BykhovDenis** [comment]
Could you also please provide workspace name?

**Comment by chekoopa** [comment]
`MyOwnAss`

**Comment by BykhovDenis** [comment]
Thank you for your feedback. Fixed for your workspace and new workspaces
