### ISSUE TITLE
Improve TxOperation workflow

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#626]
We should have more high level operations like

* updateDoc/updateCollection => `update(doc, operation)` => It should check object class hierarchy and perform appropriate updateDoc/updateCollection as desire.

* addCollection() => `add(parent, _class, attachedData)`
* removeDoc/removeCollection => `remove(doc)`

**Comment by aplatoff** [comment]
Предлагаю методы не переименовывать - это жопа по всему коду, и updateCollection оставить, просто писать что он deprecated, но хотя updateCollection может переделать на updateDoc если их не много

**Comment by haiodo** [comment]
Сейчас пока что вообще всего не много:-)

**Comment by aplatoff** [comment]
Ну я не уверен что `update` это лучше чем `updateDoc` -- это какой то бессмысленный массаж всего кода
