### ISSUE TITLE
unable to integrate with github or github orgnization repos

### ISSUE THREAD

**Issue by icarus-00** [hcengineering/platform#6284]
### Description of the issue

I have some repos that i am working on, and a github orgnization with private repos aswell, i can't integrate any of my repositories with huly, i go through the installation process, and gets redirected back to my instance, but nothing happens, i only see the the integration instructions and my repos are not loaded in, so i can't do anything with github.

### Your environment

the web based version of huly.
firefox latest stable version as of date.
windows 10.

### Steps to reproduce

go to integrations->github repositories->install github app->follow the process with either personal or orgnization repos, you can select all or specific repos-> wait 3 seconds-> redirected back to where you started with no success.

### Expected behaviour

my repos would show up with the ability to create projects connected to the repos.

### Actual behaviour

nothing
![image](https://github.com/user-attachments/assets/b7721e56-6645-4b06-a91a-12a4ed97d38e)

![image](https://github.com/user-attachments/assets/b9dda88e-eb00-4b62-b14d-74273f43c6e6)

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmIzOTZhYjllYmQxNjllZWExZmQ5N2UiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.r5eEAJFWf3DTeQpDKb5W7a15XzDVGlWpIervpFMC97Q">Huly&reg;: <b>UBERF-7836</b></a></sub>

**Comment by haiodo** [comment]
hi @icarus-00 will take a look ASAP tomorrow.

**Comment by haiodo** [comment]
Caused by

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
HttpError: Bad credentials - https://docs.github.com/rest
    at /usr/src/app/bundle.js:48666:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendRequestWithRetries (/usr/src/app/bundle.js:59710:16)
    at async requestWithGraphqlErrorHandling (/usr/src/app/bundle.js:53193:24)
    at async Job.doExecute (/usr/src/app/bundle.js:52158:22)
{"level":"error","message":"Unhandled Rejection at:","promise":{},"reason":{"message":"Bad credentials - https://docs.github.com/rest","name":"HttpError","request":{"headers":{"accept":"application/vnd.github.v3+json","authorization":"token [REDACTED]","user-agent":"octokit.js/3.2.1 octokit.js/3.2.1 octokit-core.js/5.2.0 Node.js/20.16.0 (linux; x64)"},"method":"GET","request":{},"url":"https://api.github.com/installation/repositories"},"response":{"data":{"documentation_url":"https://docs.github.com/rest","message":"Bad credentials","status":"401"},"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-length":"95","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Thu, 08 Aug 2024 04:53:41 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-frame-options":"deny","x-github-media-type":"github.v3; format=json","x-github-request-id":"70DC:2B7B11:8264DF5:F4330D6:66B44F55","x-ratelimit-limit":"60","x-ratelimit-remaining":"59","x-ratelimit-reset":"1723096421","x-ratelimit-resource":"core","x-ratelimit-used":"1","x-xss-protection":"0"},"status":401,"url":"https://api.github.com/installation/repositories"},"stack":"HttpError: Bad credentials - https://docs.github.com/rest\n    at /usr/src/app/bundle.js:48666:25\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async sendRequestWithRetries (/usr/src/app/bundle.js:59710:16)\n    at async requestWithGraphqlErrorHandling (/usr/src/app/bundle.js:53193:24)\n    at async Job.doExecute (/usr/src/app/bundle.js:52158:22)","status":401},"timestamp":"2024-08-08T04:53:41.690Z"}{
```

Digging for more details.

**Comment by haiodo** [comment]
Worker is not started for new installation, still looking, few issues are fixed and it works for staging now, but not for huly.app

**Comment by alexandreKLabs** [comment]
Just for your information: Since this morning, the Huly Github application now works, but I cannot see all my projects.

![Huly-Screenshot](https://github.com/user-attachments/assets/20f00df0-db0b-4376-b057-2625609169ac)

Keep up the good work, thank you in advance!

**Comment by haiodo** [comment]
@alexandreKLabs It shows only projects with compatible integrations, 
so if you have few integrations or installed/uninstalled, you will need to create new project for new installation of Github app. You could slack me privately your workspace name in community and I could check more carefully. Thanks.

**Comment by icarus-00** [comment]
thanks a lot, it's working for me now aswell
