### ISSUE TITLE
Issues with inviting new and kicked employees

### ISSUE THREAD

**Issue by AbigailDawson** [hcengineering/platform#6322]
Two issues related to inviting employees raised by Huly Community members:

1. Kicked employee cannot be re-invited ([link](https://hulycommunity.slack.com/archives/C06BJD10YBC/p1723217783528309))

> Hello - I could not find any way to "resend" an invite for a team member. How is this done? I then tried to "kick" them and readd, but there is no way to delete their account and now I can't un-kick them as the account already exists.
>
> says account not found now when they try the invite link
>
> says inactive next to their name and there is no way to undo this

1. ~~Invited employee unable to join using Google signup (~~[~~link~~](https://hulycommunity.slack.com/archives/C06BJD10YBC/p1723477017824399)~~)~~

> ~~Adding an employee to an existing workspace, when he signs in (tried both via Google account and email/password) and follows the invite link, there’s an error (see screens). We tried adding him into employee list in the Workspace, it didn’t help.~~

~~Screenshots provided by user for #2~~

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmJhMmUyMjEwMDhmZDk4YzJkZTJhZmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.u5r8KkxSh6mQn2VfWwkU2OJ4qaLdfCmMA6UrQ6gsU_0">Huly&reg;: <b>UBERF-7873</b></a></sub>

**Comment by lexiv0re** [comment]
Taking care of the second point of this issue.

**Comment by lexiv0re** [comment]
issue #2 is resolved
