### ISSUE TITLE
Request for Access to Private Repository

### ISSUE THREAD

**Issue by Sunilsunyruj** [hcengineering/platform#6433]
Hello,

I am Frantz Bonaparta , a software developer at Blem CRM Corporation. I am interested in gaining access to the private repository hcengineering/platform as I need to review the code for integration with our internal tools and possibly contribute some improvements.

Could you please grant me access to this repository? If there are any additional steps I need to follow or if further information is required from my side, please let me know.

Thank you for your time and assistance!

Best regards,
Frantz Bonaparta
frantzbonaparta46@gmail.com

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmNmN2ZkYmFjY2U3NzU1MjYyZmMyNTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.-1IAKJCEY_YMGXPssdguoTYGvUNlisrzCQJtOarFR6Q">Huly&reg;: <b>UBERF-7984</b></a></sub>

**Comment by aplatoff** [comment]
Dear Frantz,

Huly Platform is Open Source and all the code available to everyone (including you) at https://github.com/hcengineering/platform under EPL license. In other words this is public repository.

Please let me know if we can help with anything else, in the meantime let me please close this request as resolved.

Kind regards,
Andrey
