### ISSUE TITLE
Two company fields in Vacancy settings

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6536]
![image.png](https://front.hc.engineering/files?workspace=platform&file=292fdbde-561b-416f-bba7-af1cc5dfde90&width=720 "image.png")

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmUxYmNjZDU3NmVmNDVmNWU3YmJjMGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.4EqQeuwDsStOGevI_ZjWp1KJnyDhhMVTLq4Soam474A">Huly&reg;: <b>UBERF-8082</b></a></sub>

**Comment by Chunosov** [comment]
<https://github.com/hcengineering/platform/pull/7422>
