### ISSUE TITLE
Bug: In chat, clicking 'Show more' on description change causes freeze

### ISSUE THREAD

**Issue by AbigailDawson** [hcengineering/platform#6561]
**Summary**

In the chat, clicking `Show more` on a document that has changes causes the app to freeze. It can  be unfrozen with page refresh. I don’t have any other issues in chat to compare it to so I don’t know if it’s just happening with this specific issue [EZQMS-1173](https://front.hc.engineering/browse/?workspace=platform&_class=tracker%3Aclass%3AIssue&_id=66bb3007e35c5acbcbe6f9fc&label=EZQMS-1173) 

**Steps to reproduce:**

1. Login to platform
2. Navigate to chat
3. Find an issue that has had changes to the description
4. Click `Show more`

**Actual Result**

Clicking `Show more` should reveal the changes.

**Expected Result**

Clicking `Show more` causes the app to freeze.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmU0MzM1MjVhZGQ5ZTRhYmRjY2NlNTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.rUinLnzOSWvnbi2fidBo8G5E40uauUlnMzvO_jimucI">Huly&reg;: <b>UBERF-8104</b></a></sub>

**Comment by kristina-fefelova** [comment]
Should be fixed now
