### ISSUE TITLE
Update issue example with proper collaborative content upload

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6571]
Please update examples, to properly pass/update content of collaborative fields.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmU3OWRiNjNhNDA1YTM1ODlmYTY2N2IiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.C0Act-lY29dzksnwxpey4RSc35oZgEOYWBSGa0dYvrk">Huly&reg;: <b>UBERF-8119</b></a></sub>

**Comment by aonnikov** [comment]
[Andrey Sobolev](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Andrey%20Sobolev) do we already have examples documented somewhere?

**Comment by haiodo** [comment]
I suppose so 😄
