### ISSUE TITLE
Add document content tests

### ISSUE THREAD

**Issue by kakRostropovich** [hcengineering/platform#6593]
* Add tests for image manipulations
* Add tests for slash menu inside document
* Add tests for navigation of a document
* Add test for adding a document to a document
* Make `data-id` attribute a default attribute to use getByTestId locator
* Check fixes of bugs

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmU4ODJiYjU2YTcxNjQ4OTUzYTZkOGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.MK4eonIRRQGdeUf2-lKVPWhoFpCxaMrNXiLz0shRD10">Huly&reg;: <b>UBERF-8141</b></a></sub>

**Comment by stephen-mtz** [comment]
I can work on this if no one is already on it
