### ISSUE TITLE
Question in todo visibility in planner >> i) When I select "visible to everyone", in planner: "Busy" and ii) when I select  "freebusy", in planner: "work slot" - is that expected behavior?

### ISSUE THREAD

**Issue by charles-rollet** [hcengineering/platform#6667]
Question in todo visibility in planner >> i) When I select "visible to everyone", in planner: "Busy" and ii) when I select  "freebusy", in planner: "work slot" - is that expected behavior? 

<https://front.hc.engineering/workbench/hulydemo/team>

I) I set as “visible to everyone”

![Capture d’écran 2024-09-22 à 13.32.21.png](https://front.hc.engineering/files?workspace=platform&file=3492a67e-be23-499d-a7ff-2246885615fc&width=707 "Capture d’écran 2024-09-22 à 13.32.21.png")

I) I set as “freebusy”

![Capture d’écran 2024-09-22 à 13.32.03.png](https://front.hc.engineering/files?workspace=platform&file=f8745e59-8f04-47db-89fe-df7184e4203b&width=737 "Capture d’écran 2024-09-22 à 13.32.03.png")

Is it expected? 

looping in [Andrey Platov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=62c40aa9e5a6ae23d8307df0&label=Andrey%20Platov) too 😉  

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYwMDA1YTEzNTdlNDAxYjg5NjIxNzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.XfNCMqmAh594rm-4Q75pnCvex3XiT-x3chho1rpd_3k">Huly&reg;: <b>UBERF-8215</b></a></sub>

**Comment by AbigailDawson** [comment]
The “Busy” slot is expected. You should only notice this for action items that are not connected to the project you are viewing - this could be action items connected to a different project, or action items that have been manually entered in your planner. This is a privacy protection, so people’s action items will only be visible within the team planner for the project they’re connected to. If someone has action items for a different project, those action items shouldn’t show up on someone else’s project - they should just be able to see that that person is busy during that time.

As for “Work Slot”, I’m not sure why we would show “Busy” vs. “Work Slot” in this scenario. I believe this might be related to [UBERF-8214](https://front.hc.engineering/browse/?workspace=platform&_class=tracker%3Aclass%3AIssue&_id=66eff74fc49c8e621d2c767e&label=UBERF-8214).
