### ISSUE TITLE
Integration >> is the gmail integration supposed to work? I tried and nothing appears to be integrated - I tried to send an email to see if I could see it in the inbox, but nothing. Maybe I missed the point

### ISSUE THREAD

**Issue by charles-rollet** [hcengineering/platform#6669]
Integration >> is the gmail integration supposed to work? I tried and nothing appears to be integrated - I tried to send an email to see if I could see it in the inbox, but nothing. Maybe I missed the point

<https://front.hc.engineering/workbench/hulydemo/team>

So, it looks like this in settings: 

![Capture d’écran 2024-09-22 à 17.00.57.png](https://front.hc.engineering/files?workspace=platform&file=5f0c3ffe-e8c9-4961-be1f-ed8cb40c7229&width=375 "Capture d’écran 2024-09-22 à 17.00.57.png")

Maybe I did something wrong - would you be able to help or I loop in the devs? 

looping in [Andrey Platov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=62c40aa9e5a6ae23d8307df0&label=Andrey%20Platov) too 😉  

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYwMzE0NzEzNTdlNDAxYjg5NjIxOTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.Ofd_sdWgjADXH_eCPJ5llWQZNAINDCffXCxwG9GDd4I">Huly&reg;: <b>UBERF-8217</b></a></sub>

**Comment by AbigailDawson** [comment]
No, not yet. We can add your email manually if you want to test it, just let me know.

**Comment by charles-rollet** [comment]
Ok, let’s close it then

**Comment by fakebizprez** [comment]
Any update on this?

![image](https://github.com/user-attachments/assets/6dd2e7c4-6a4c-44ea-93c7-670cce88f161)

**Comment by charles-rollet** [comment]
Yeah - would be great to test it 🙂
