### ISSUE TITLE
Telegram integration >> I cannot integrate with my telegram

### ISSUE THREAD

**Issue by charles-rollet** [hcengineering/platform#6670]
Telegram integration >> I cannot integrate with my telegram

<https://front.hc.engineering/workbench/hulydemo/team>

So, it looks like this in settings: 

![Capture d’écran 2024-09-22 à 17.37.17.png](https://front.hc.engineering/files?workspace=platform&file=9c369c8d-a0c3-448e-a0c0-5945382efcd5&width=1275 "Capture d’écran 2024-09-22 à 17.37.17.png")

Then I try to send a notification, and I dont receive anything on Telegram

![Capture d’écran 2024-09-22 à 17.37.53.png](https://front.hc.engineering/files?workspace=platform&file=12fb95d2-2a33-4b2e-ba36-3faa0ae5efe2&width=976 "Capture d’écran 2024-09-22 à 17.37.53.png")

Maybe I did something wrong - would you be able to help or I loop in the devs? 

looping in [Andrey Platov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=62c40aa9e5a6ae23d8307df0&label=Andrey%20Platov) too 😉  

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYwMzllMDEzNTdlNDAxYjg5NjIxYTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.LK7xAV2kNGZbhMt_qmW5MTaGhirABlcXf9Zv6AQqjXc">Huly&reg;: <b>UBERF-8218</b></a></sub>

**Comment by AbigailDawson** [comment]
Did you configure Telegram in your Notifications settings? What did you see on the Telegram side when you set up the integration?

**Comment by MishaMgla** [comment]
Experience similar issue.
**Steps I have made:**
1. Connected telegram account, confirmed by code at settings>integrations page.
2. Turn on Telegram in settings>notifications>chat page.
3. Sent message via chat at huly app to this account.
No messages from huly.app appears in Telegram.
I checked that huly.app session exist in Telegram app
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/d12020b2-64f0-4a4a-84a2-f66620528cb0">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/2974ec36-dc04-46c1-9406-2db4cdf6f5fc">
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/135b4c6a-4926-42a8-a6cc-4c00737978cd">

.
