### ISSUE TITLE
Bug: Event participants cannot see events they're added to

### ISSUE THREAD

**Issue by AbigailDawson** [hcengineering/platform#6689]
**Summary**

It seems like you can add participants to an event but the participants won’t see the event in their own planner or receive any kind of notification. This issue was found on **front**.

**Steps to reproduce:**

1. Create an event in the planner
2. Add a participant
3. Save the event

**Actual Result**

Participant should receive a notification and/or see the event in their own planner

**Expected Result**

Participant does not see anything in their planner or receive notification; they have no way of knowing whether they’ve been added to someone’s event.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYxNGY2MDI5ZGM1ZTdmMzI0NTVhZGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.ULiKt5MDb4yEjrhdDwljG8ri_JJa4HW6Q2mzcQU-4VU">Huly&reg;: <b>UBERF-8237</b></a></sub>

**Comment by oaydogmus** [comment]
Hello, thank you for the great effort you put into the project. Our team also thinks this is crucial for UX. We hope it gets implemented soon. I subscribed to the issue. We wish you the best.

**Comment by BykhovDenis** [comment]
Hello. It will be fixed in the next version, we're going to deploy it in this week
