### ISSUE TITLE
Invalid value is stored inside blob

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6739]
```
{"_id":"004cef89-317c-4819-9c14-7cd7ebaba57f","bufferSize":0,"contentType":"audio/ogg","domain":"blob","level":"error","message":"download blob size mismatch","name":"w-anastagal4-idgi-66ad466b-5fe17f3163-2a489a","provider":"s3","size":{"value":663368},"timestamp":"2024-09-26T11:46:10.101Z","workspace":"w-anastagal4-idgi-66ad466b-5fe17f3163-2a489a"}
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmY1NGE2MDFjYjUwNjYzZTU5MzMwNjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.pdKeacOFUqg8jkxp2IAQKS2WlXdyYCJIa84dqrkx_ks">Huly&reg;: <b>UBERF-8287</b></a></sub>

**Comment by haiodo** [comment]
It is related to backup probable, but I think we could close it already.

**Comment by aonnikov** [comment]
[Andrey Sobolev](https://front.hc.engineering/browse/?workspace=bb793ec1-252e-4419-8998-7f220ababdfa&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Andrey%20Sobolev) do we still need this? I guess it was related to chrome plugin.
