### ISSUE TITLE
Feat: Deleting and editing labels

### ISSUE THREAD

**Issue by AbigailDawson** [hcengineering/platform#6741]
Several users in the community have asked about deleting and editing labels and this seems to be a very highly requested feature.

Users should be able to delete and edit labels, which would remove or update the label on all associated issues.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmY1NTA3OTFjYjUwNjYzZTU5MzMwOGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.lSo0OZ0G84N_NEjdFVUBbSggHg7J4CRoYScOdQE1r3U">Huly&reg;: <b>UBERF-8289</b></a></sub>

**Comment by yohann84L** [comment]
Any progress on this? This is a basic setting from any project management tool

**Comment by AbigailDawson** [comment]
> Any progress on this? This is a basic setting from any project management tool

Yes, this is now available in the Tracker under "Labels" in the left sidebar. You can edit and delete labels, add descriptions and see how many issues have been tagged with each label.
