### ISSUE TITLE
Workspace selector sort order are reversive

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6791]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZlNGVlNmU3OTVmNWE2MjkzZjQ4NmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.yGnpR0L_U8qOLyTq86WhH7ivRLXcbnZS8YJIS0kpzjc">Huly&reg;: <b>UBERF-8339</b></a></sub>

**Comment by lexiv0re** [comment]
[Andrey Sobolev](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Andrey%20Sobolev) most likely related to the account changes, let me take a look

**Comment by haiodo** [comment]
Nope, we have sorting in UI

**Comment by lexiv0re** [comment]
Oh, ok then.
