### ISSUE TITLE
PG controlled migration of accounts schema

### ISSUE THREAD

**Issue by lexiv0re** [hcengineering/platform#6877]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA4Zjg5MDI5ZGY3ZTAyMGFhNWI1ZWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.oUXCtLKUQALeV_ICNDx4FhbswtGOWTHJE-38IF44z80">Huly&reg;: <b>UBERF-8426</b></a></sub>

**Comment by AdityaGupta-cyber** [comment]
I can see that you have already self assigned this to yourself. But can you please give a brief about this bug?
