### ISSUE TITLE
slack invite link on docs site is outdated - not accessible

### ISSUE THREAD

**Issue by seccentral** [hcengineering/platform#6879]
### Description of the issue

Clicking the slack link on https://docs.huly.io/ shows a login restricted to @hardcoreeng.com domain :

> Don’t have an @hardcoreeng.com email address?
> Contact the workspace administrator at Huly Community for an invitation.

The link on the main website's menu under Community works just fine

### Possible solutions

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA5MDAzZDI5ZGY3ZTAyMGFhNWI2MmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.m8mhakhoViyMXfruzaRhLrjKRLJydlxU-oRsayf4UHQ">Huly&reg;: <b>UBERF-8428</b></a></sub>

**Comment by aplatoff** [comment]
Thank you very much! Updating now, there is Slack limit of 400 persons per link even if link never expires
