### ISSUE TITLE
Huly

### ISSUE THREAD

**Issue by emreislyn** [hcengineering/platform#6895]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhMzc3NGRhN2FlYjk5YTc3NDU0ZTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.4a7PvhTeCqfBN7kFfippRkTQt_gy10ZXbE5zmjZBPro">Huly&reg;: <b>UBERF-8443</b></a></sub>

**Comment by aplatoff** [comment]
yes! 💯 👍
