### ISSUE TITLE
Excuse me. Is the portal page open source?  (https://huly.io/)

### ISSUE THREAD

**Issue by jeff-fe** [hcengineering/platform#6896]
Excuse me. Is the portal page open source?  (https://huly.io/)

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhMzhjNGRhN2FlYjk5YTc3NDU1MDkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.2F2arQUVNh7XlnguZ7xGq5-aq4TbsqAmBw50pb-Mqno">Huly&reg;: <b>UBERF-8444</b></a></sub>

**Comment by BykhovDenis** [comment]
Website created by https://pixelpoint.io/ we do not have any objections to open source it, but it will be useless for you. Visuals rendered as videos or rive files/
