### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by PILBABA** [hcengineering/platform#6901]
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhZjUxNzA4YzM5MmYxMDU1OTU1NzUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.0H8cYs2zp_hwNTR080URrRLhE0gxQ4gFGs9aXAQue48">Huly&reg;: <b>UBERF-8450</b></a></sub>

**Comment by aplatoff** [comment]
thank you!
