### ISSUE TITLE
Bug: Authorize GitHub Huly App appears clickable even after authorizing

### ISSUE THREAD

**Issue by AbigailDawson** [hcengineering/platform#6922]
**Summary**

I have a workspace with a project connected to a GitHub repo and everything appears to be syncing as expected, but the button remains in the corner `Authorize Huly GitHub App`:

![Screenshot 2024-10-14 at 4.38.36 PM.png](https://front.hc.engineering/files?workspace=platform&file=9afcee7b-f622-4fbe-b120-54b1f07aa341&width=258 "Screenshot 2024-10-14 at 4.38.36 PM.png")

When clicked, I see `Processing authentication/installation` but it just returns back to the original page and nothing changes with the button.

On the GitHub repo the Huly app is installed and everything looks fine on that end.

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBkODIxMjVjZTU0NjMyNTcwZDgxM2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.qKfYRmHz0znwSIr0EJyhgCeMCkUPGH5G24SpH1-amt8">Huly&reg;: <b>UBERF-8471</b></a></sub>

**Comment by RED-ROSE515** [comment]
Hello @haiodo , @AbigailDawson  I have contributed many open-source projects.
And I would like to work on this project.
How can I start contributing?
Thanks.
