### ISSUE TITLE
Unable to tag (@mention) the person who created the workspace

### ISSUE THREAD

**Issue by jyungtong** [hcengineering/platform#6951]
### Description of the issue

Unable to tag (@mention) the person who created the workspace

### Your environment

* Version of Huly: 0.6.325
* Browser (and version): Firefox 131.0.2
* Your operating system (and version): Ubuntu 22

### Steps to reproduce

1. Create a new workspace with Google SSO sign in
2. Invite collaborators
3. From collaborator, go to `#general` type `@{owner name}`

### Expected behaviour

Should see owner name and able to mention the owner

### Actual behaviour

No owner name is found in the autocomplete list

### Possible solutions

N/A

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1M2E2YzUzNmNiMTQyNWExMTU3YTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.FybD__Hnr__9fBIJ3Q4rRrGEbLxLCv8SXQApMC_422E">Huly&reg;: <b>UBERF-8632</b></a></sub>

**Comment by KingkorAtMaxint** [comment]
This is a really annoying issue. Is there any fix incoming?

**Comment by BykhovDenis** [comment]
It’s already fixed for new workspaces, but we can’t automatically fix it for existing workspaces that might still be affected. If you encounter this issue, please provide your workspaceUrl, and we will resolve it for you.
