### ISSUE TITLE
[BUG] Critical error after refresh page

### ISSUE THREAD

**Issue by Darginec05** [hcengineering/platform#6966]
### Description of the issue

Error after refresh page

### Your environment

* Prod
* Chrome
* Mac M3

### Steps to reproduce

- Open page https://huly.io/
- Refresh page

### Expected behaviour

No crash after refresh page

### Actual behaviour

Error after refresh page

https://github.com/user-attachments/assets/2cb4f75e-ddc3-4809-bc7b-80ebe71e1869

**Comment by aplatoff** [comment]
Thank you very much! Caching issue, should be fixed now
