### ISSUE TITLE
Does huly have API?

### ISSUE THREAD

**Issue by FromNetToDev** [hcengineering/platform#6996]
is there an API where I can read it? Any documentation on API or webhook?

**Comment by Horoli** [comment]
I need too.

**Comment by pat-mw** [comment]
+ 1 !!

**Comment by tyler-wright** [comment]
What you guys are building here is great, amazing work.

I just wanted to add to this discussion about API's to say that I think the number one missing feature for me for adopting a product like Huly in my business would be the lack of an API to pull out time records and bill them with accounting software. It's difficult to move to any project management system as a consultancy that doesn't have robustly query-able (via API) time records.

I'm sure its on your roadmap, but thought I'd mention it anyway. Good luck moving towards your 1.0

**Comment by ikethepike** [comment]
I'd love to build a vscode extension for time tracking 👌

**Comment by clomads** [comment]
+1

**Comment by squintdev** [comment]
Definitely something that would help a lot!

**Comment by rybkinevg** [comment]
+1

**Comment by bls-media** [comment]
same here!! Please give us an update if you plan to implement it :)

**Comment by lexiv0re** [comment]
We have released a new package which is an API client to Huly platform.
The client exposes methods to connect and interact with the core Huly functionality.  You can find usage examples in our repository: https://github.com/hcengineering/huly-examples/tree/main/platform-api

**Comment by szawadski** [comment]
Beyond those examples, is there going to be more detailed documentation over all the available API and eventually some public REST endpoints with OpenAPI documentation?

**Comment by mydnic** [comment]
This project does need a REST API out of the box

**Comment by nathan-de-pachtere** [comment]
Could be amazing to have a clean API doc. 

A good inspiration is Dokploy https://docs.dokploy.com/ with their API approach https://docs.dokploy.com/docs/api -> everything in the interface can be done through the API.

**Comment by franz-josef-kaiser** [comment]
Too bad. That's a deal breaker for us as it would be the only of the services we use without an API and we do not have a use for an island solution. Thanks for the work tough.

**Comment by wafelmolt** [comment]
+1

The Web API should be accessible outside of JS context even though @hcengineering/api-client is cool and has nice features.
I also don't really like the fact that @hcengineering/api-client uses username/password credentials for authentication. Having at least web tokens, API key or OIDC support should be a minimum.

**Comment by onyedikachi-david** [comment]
> We have released a new package which is an API client to Huly platform. The client exposes methods to connect and interact with the core Huly functionality. You can find usage examples in our repository: https://github.com/hcengineering/huly-examples/tree/main/platform-api

I am getting this error, is the package published on npm?

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@hcengineering%2fapi-client - Not found
npm ERR! 404 
npm ERR! 404  '@hcengineering/api-client@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2025-04-30T16_19_55_538Z-debug-0.log
```

**Comment by wafelmolt** [comment]
@onyedikachi-david package seams hosted on github registry : https://github.com/hcengineering/platform/pkgs/npm/api-client

Please try to not pollute issues. Next time, open a dedicated one.

**Comment by chudnyi** [comment]
I am using a self-hosted instance of Huly with SSO auth. The user does not have a password. I can't find a way in the Huly interface to create a token for use in the `api-client`. Please explain to me how to create a token for the API.

**Comment by chudnyi** [comment]
Please tell me how to get an api token
