### ISSUE TITLE
Russian translations missed

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#7022]
* All projects
* Human resources

Original: https://hulycommunity.slack.com/archives/C06DZ5A8TMK/p1729617315639139

![image (14)](https://github.com/user-attachments/assets/33ff8f20-43b9-40ab-8db1-f3d4d56a1866)

**Comment by Bramfoxie** [comment]
"All projects" - was fixed in this merge https://github.com/hcengineering/platform/pull/7215

**Comment by Bramfoxie** [comment]
"Human resources" - was fixed in this merge https://github.com/hcengineering/platform/pull/7282

@aonnikov the issue can be marked as solved.

**Comment by aonnikov** [comment]
@MilanovaSmile thanks, closed
