### ISSUE TITLE
`Select All` checkbox wrong behavior

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#7023]
Mess in Select All checkbox state

Original: https://hulycommunity.slack.com/archives/C06DZ5A8TMK/p1729617461613599

![image (15)](https://github.com/user-attachments/assets/f3b09fd4-d8dd-4add-83b5-0127d1d2be15)

**Comment by eniiku** [comment]
hi @aplatoff. Can I take up this issue?

**Comment by ArtyomSavchenko** [comment]
The issue have been fixed
