### ISSUE TITLE
Slack Invitation no longer active

### ISSUE THREAD

**Issue by jschneider** [hcengineering/platform#7067]
Your link is outdated:

https://hulycommunity.slack.com/join/shared_invite/zt-2rww27st2-FO37Hj72YoxYKLt2C8p79A#/shared-invite/error

**Comment by BykhovDenis** [comment]
Hello. Thank you. Fixed. Please use [https://huly.link/slack](https://huly.link/slack)

**Comment by lifeforced** [comment]
> Hello. Thank you. Fixed. Please use https://huly.link/slack

@BykhovDenis  This no longer works

**Comment by lifeforced** [comment]
A Discord server would likely be more practical.
