### ISSUE TITLE
Telegram connection not working

### ISSUE THREAD

**Issue by slarrain** [hcengineering/platform#7101]
### Description of the issue

When I click Add on the Telegram Integration, it asks for my phone number. I add it, click on Connect, and stays in "Connecting" indefinetely.

### Your environment

* Version of Huly: 0.6.343
* Browser (and version): N/A - AppImage version.
* Your operating system (and version): Ubuntu 24.04

### Steps to reproduce

try to connect to the Telegram account

### Expected behaviour

Actual connection to Telegram.

### Actual behaviour

Stays forever in connecting
![Pasted image (11)](https://github.com/user-attachments/assets/62e7eb3e-ae37-4585-90af-3597dda2d10d)

### Possible solutions

(Not obligatory)
If you know how to fix the bug, please describe your solution here.

**Comment by lexiv0re** [comment]
Hello @slarrain, thanks for your interest in Huly. I'm assuming you want the telegram integration for notifications from the platform. If that is the case you don't really need to integrate it via the integrations page but enable it in the Notifications tab of the settings. You'd then only be asked to interact with the telegram bot and everything will be done.

**Comment by slarrain** [comment]
Thank you. That works.
What is the Telegram integration supposed to do then?

**Comment by lexiv0re** [comment]
It's creating a Telegram client connected to your Telegram account so you can message and receive messages in Huly the same way as you'd do from your Telegram client.
To my knowledge it's not very stable at the moment. Also the UX is gonna be reworked completely to integrate it into the chat properly.

**Comment by slarrain** [comment]
OK. Closing then. Thanks.
