### ISSUE TITLE
model version mismatch

### ISSUE THREAD

**Issue by itswl** [hcengineering/platform#7136]
### Description of the issue

{"email":"test@test.com","extra":"{\"confirmed\":true,\"productId\":\"\"}","level":"warn","message":"model version mismatch","timestamp":"2024-11-08T09:28:02.186Z","version":"0.6.349","workspace":"w-koofranker-naturalselec-664eec16-17b45e2bd0-b2b1c9","workspaceUrl":"naturalselection","workspaceVersion":"0.6.248"}

### Your environment
huly v0.6.248 to v0.6.349

how to fix it? thanks

**Comment by lexiv0re** [comment]
Hello @itswl, is it cloud or self-hosted version?

**Comment by itswl** [comment]
> Hello @itswl, is it cloud or self-hosted version?

self-hosted

**Comment by lexiv0re** [comment]
Please take a look at configuring this service https://github.com/hcengineering/huly-selfhost/blob/main/template.compose.yaml#L59 which might be missing in your deployment.

**Comment by itswl** [comment]
> Please take a look at configuring this service https://github.com/hcengineering/huly-selfhost/blob/main/template.compose.yaml#L59 which might be missing in your deployment.

Thank you, this worked!!!
