### ISSUE TITLE
Brand name

### ISSUE THREAD

**Issue by Maxttier** [hcengineering/platform#7140]
---

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1NDM1MjUzNmNiMTQyNWExMTczZjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.u_6ams2T1p0IeYV9D-Ebst-0I3Olldfma1qA9Qro_1Y">Huly&reg;: <b>UBERF-8721</b></a></sub>

**Comment by aplatoff** [comment]
This is not a linguistics experts forum, this is a place for technical matters. Closing as irrelevant
