### ISSUE TITLE
[Feature Request] Chat Webhooks

### ISSUE THREAD

**Issue by T3ch404** [hcengineering/platform#7182]
### Feature Request Description

I didn't see an issue for this feature specific to the Huly Chat app yet. My team uses various external tools that use Slack or Discord's web-hooks & API endpoints in order to send messages about automation statuses, log events, etc. Based on the Huly documentation I see no implementation of web-hooks or API endpoints to send messages in the Huly Chat app. Adding web-hooks or API endpoints for this use case could open the door for all sorts of 3rd party app support

### Example Documentation

Discord - https://discord.com/developers/docs/resources/webhook
Slack - https://api.slack.com/quickstart

**Comment by lexiv0re** [comment]
Hello @T3ch404, please take a look at https://github.com/hcengineering/huly-examples/tree/main/platform-api

**Comment by T3ch404** [comment]
@lexiv0re, Thanks for responding so quickly! I see there are examples for interacting with Projects/Issues through the API, but no documentation on interacting with the Chat app? Maybe I'm missing something.. I'll try to play around with the API example you posted later this evening.

**Comment by lexiv0re** [comment]
The API is the same for any object in a workspace whether it's a project/issue or a chat message. You just need to use the message class with this client. You can find all classes models here: https://github.com/hcengineering/platform/tree/develop/models. 
E.g. for a chat message it would be https://github.com/hcengineering/platform/blob/develop/models/chunter/src/types.ts#L85 and the class to use is `chunter.class.ChatMessage` correspondingly. You'll need to import `@hcengineering/chunter` package to get chat classes metadata available in your script.

**Comment by mydnic** [comment]
Any chance to make this a built in feature ? Because right now we have to develop some sort of bridge system to make it work
