### ISSUE TITLE
Bug: Unable to @mention a workspace member

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#7311]
**Summary**

This was reported in workspace **test-t2w**. A user created the workspace, invited several team members, and then transferred ownership of the workspace to another user.

Now, in the `Employee` tab in Contacts, the user who originally created the workspace shows the `Customer` role on their contact:

![Screenshot 2024-10-18 at 8.58.42 AM.png](https://front.hc.engineering/files/bb793ec1-252e-4419-8998-7f220ababdfa/bb7287b9-8124-4ae6-95f6-a3b376b8d7fd&width=1185 "Screenshot 2024-10-18 at 8.58.42 AM.png")

Also, other team members cannot @mention this user (their name is not available to tag).

**Comment by AbigailDawson** [comment]
Found another issue where this was reported: <https://github.com/hcengineering/platform/issues/6951>

**Comment by ZenDevMaster** [comment]
I am experiencing a similar bug - a recently added team member cannot be linked to an @mention. I am the owner and creator of the workspace.

Screencast attached with example:
https://github.com/user-attachments/assets/e19c8c2b-ddea-47ec-9699-cce081854af4

**Comment by ArnoChenFx** [comment]
How to fix this issue for a self-hosted huly? It seems the problem still exists even after upgrading to the latest version.
