### ISSUE TITLE
ezQMS project - I cannot see them anymore in tracex.hc or hc.front and ii) it is not in the list of All project either

### ISSUE THREAD

**Issue by charles-rollet** [hcengineering/platform#7331]
ezQMS project - I cannot see them anymore in tracex.hc or hc.front and ii) it is not in the list of All project either

When I open <https://tracex.hc.engineering/workbench/platform/tracker/EZQMS-1213> it says `object does not exist or I do not have access to it` 

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1M2NkNTUzNmNiMTQyNWExMTVlZjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.gPE63w4_-xlNGZPhr9Ncw8NMGbY8Cp1cmEoRe5VT61I">Huly&reg;: <b>UBERF-8541</b></a></sub>

**Comment by lexiv0re** [comment]
[Charles Rollet](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=64708c79c8f2613474dea38b&label=Charles%20Rollet) all done, should be available now 😉

**Comment by charles-rollet** [comment]
I confirm 😉

**Comment by charles-rollet** [comment]
thx 😉
