### ISSUE TITLE
Question from QARA (putting it in this project as I do not have access to ezqms one any more) >> requesting if TraceX can support documents in Thaï language - assuming yes, but checking just in case ;-)

### ISSUE THREAD

**Issue by charles-rollet** [hcengineering/platform#7333]
Question from QARA (putting it in this project as I do not have access to ezqms one any more) >> requesting if TraceX can support documents in Thaï language - assuming yes, but checking just in case ;-) 

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1M2NkYTUzNmNiMTQyNWExMTVmMGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.t9Me-msIo1hinFP4g7vQsr9r5FVS8N_7gbBWKtdEoSY">Huly&reg;: <b>UBERF-8543</b></a></sub>

**Comment by lexiv0re** [comment]
[Charles Rollet](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=64708c79c8f2613474dea38b&label=Charles%20Rollet) yes, should be no problem having docs in any language

**Comment by charles-rollet** [comment]
[Alexey Zinovyev](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63fefffb6e876eaf328df878&label=Alexey%20Zinovyev) gracias amigo 😉
