### ISSUE TITLE
Bug: Drawing board - Duplicating text box

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#7408]
**Summary**

When adding a text box on the drawing board, a duplicate text box is created.

**Steps to reproduce:**

1. Open a drawing board
2. Add a text box and type some text
3. Click and drag the text box to reveal the duplicate text box beneath it

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU3ZGQ1YzE4OWNkMzEwMDNiMDZhZmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.Ys7q2vyQng6SOXzXHM4uxvo0O_udhRnvIMDLaO-EN_o">Huly&reg;: <b>UBERF-8853</b></a></sub>

**Comment by Chunosov** [comment]
<https://github.com/hcengineering/platform/pull/7412>
