### ISSUE TITLE
Bug: Drawing board - clicking X on empty text box deletes 1st text box

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#7411]
**Summary**

When you click X on an empty text box, it will delete the 1st text box created.

**Steps to reproduce:**

1. Open a drawing board
2. Add a text box with some text
3. Add another (empty text box)
4. Click X on the empty text box

**Actual Result**

1st text box disappears

**Expected Result**

empty text box should disappear

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU3ZWE2YTE4OWNkMzEwMDNiMDc4ZTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.rOlytRWe5EwHElRil9klpvSsATnFibWAVcFBR7DyhRE">Huly&reg;: <b>UBERF-8854</b></a></sub>

**Comment by Chunosov** [comment]
<https://github.com/hcengineering/platform/pull/7412>
