### ISSUE TITLE
Open same dialog multiple times

### ISSUE THREAD

**Issue by EgorBlagov** [hcengineering/platform#742]
Using this link I can open same dialog again

![image](https://user-images.githubusercontent.com/35273613/147563213-b9b9585d-5522-40d4-930d-5d5c76f5202b.png)

It stacks on top of each other, and seem to slow down the performance

![image](https://user-images.githubusercontent.com/35273613/147563247-cc3738da-d747-45f6-bddf-c50b3fc212ba.png)

And to exit I need to close all the dialogs

**Comment by haiodo** [comment]
Fixed.
