### ISSUE TITLE
Choose one calendar when import google calendar

### ISSUE THREAD

**Issue by LiloueG** [hcengineering/platform#7427]
### Description of the issue

When I want to import Google Calendar, I can't choose which calendar to display on the planner. This is unfortunate because, as a student, I only need the calendar with my classes to organize my days.

**Comment by BykhovDenis** [comment]
Hello. You can set it after connect integration click "Configure"

**Comment by LiloueG** [comment]
When I click on configure, i saw this popup and i can't click anwhere to change something.

![image_2024-12-11_130955557](https://github.com/user-attachments/assets/95a9cfe9-2ff4-401d-a36c-af8d38dff288)

**Comment by BykhovDenis** [comment]
Thank you. We will fix this bug in next version
