### ISSUE TITLE
Bug: Drawing board - "Show more" after deleting drawing board causes freeze

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#7466]
**Summary**

If you add a drawing board and then delete it, clicking “Show more” in the activity section for that change causes the page to freeze & error message in console.

**Steps to reproduce:**

1. Open a document
2. Create a drawing board
3. Make some changes (I had to add text for anything to show up in the Activity section)
4. Delete the drawing board
5. Click “Show more” on the change in the Activity section

![Screenshot 2024-12-11 at 9.44.33 AM.png](https://front.hc.engineering/files?workspace=platform&file=d94b1efc-6e95-427e-bbe5-9febec1874b0&width=1039 "Screenshot 2024-12-11 at 9.44.33 AM.png")

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVjNjAwY2FhYzU4OTk4NTIyNWM5OTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.uNArKZnjoz45OwJ4dHx6P0sIdfvTx_StgclkC8dBgWg">Huly&reg;: <b>UBERF-8885</b></a></sub>

**Comment by Chunosov** [comment]
Fixed in <https://github.com/hcengineering/platform/pull/7487>
