### ISSUE TITLE
Notifications for channels

### ISSUE THREAD

**Issue by aplatoff** [hcengineering/platform#844]

**Comment by omkoneva** [comment]
Дабы не плодить дубликат уточню:) Эта таска про то, чтобы приходили нотификации человеку, которого мы упоминаем в карточке какого-то кандидата? Или она про что-то другое?   

Мне бы хотелось, чтобы нотификации приходили в почту тому, кого мы упоминаем + чтобы карточка в самой Платформе у него как-то подсвечивалась. Если эта задача - про другое, напишу про это отдельно

**Comment by BykhovDenis** [comment]
Конкретно эта - про другое. Про отметки о новых сообщениях в контактной информации, например в телеграмм

**Comment by omkoneva** [comment]
Поняла. Тогда создам новую задачу :)
