### ISSUE TITLE
Несколько одинаковых рекрутеров в выпадающем списке 

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#863]
Не понятно, какую себя выбирать: 

![Снимок экрана 2022-01-25 в 14 20 34](https://user-images.githubusercontent.com/22656886/150929834-ddcf7507-7551-4231-acd8-e4307593a3a5.png)

**Comment by haiodo** [comment]
Там из за ранней версии дубликаты возникли, поменяй себе аватарку в настройках и будешь различать.

**Comment by omkoneva** [comment]
Ок, сделаю. Но почистить дубликаты всё равно не будет лишним :)

**Comment by haiodo** [comment]
This is already fixed.
