### ISSUE TITLE
Нельзя прикрепить рекрутера к кандидату, если он уже назначен на какую-то вакансию

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#864]
Сначала назначила кандидатов на вакансию - теперь не могу назначить себя на этих кандидатов, потому что софт просит выбрать вакансию, но повторно назначить этих кандидатов на вакансию нельзя 

![Снимок экрана 2022-01-25 в 14 23 51](https://user-images.githubusercontent.com/22656886/150930206-31696a2a-7adc-4ce0-b3e0-2465d947c162.png)

**Comment by haiodo** [comment]
Assign recruited нужно использовать для назначения рекрутера, на одну вакансию кандидата можно добавить только 1 раз.

<img width="607" alt="Screenshot 2022-01-25 at 15 20 25" src="https://user-images.githubusercontent.com/477235/150938606-738eb9fa-5c35-4207-b9df-5d008eb301e2.png">

**Comment by omkoneva** [comment]
Это понятно, но что делать, если сразу не добавили рекрутера в карточку кандидата? 

Я создала сегодня несколько карточек, сразу добавила кандидатов на вакансию, а себя не выбрала. Быстро опомнилась и хотела себя назначить на этих кандидатов, но не получилось, так как для этого нужно выбрать вакансию. Выбрать ту вакансию, на которые кандидаты уже назначены, я не могу. Но без этого добавить меня/Таню или любого другого менеджера также не получается

**Comment by omkoneva** [comment]
Думаю, что будет удобно, если можно будет добавить рекрутера постфактум (если сразу этого не сделали при назначении на вакансию) или наоборот. Или я что-то не то делаю? :)
