### ISSUE TITLE
Убрать вакансии, находящиеся в архиве, из выпадающего списка

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#865]
Сейчас из выпадающего списка появляются все вакансии подряд. Это неудобно: 

![Снимок экрана 2022-01-25 в 14 36 46](https://user-images.githubusercontent.com/22656886/150933804-c1365b4f-7a2d-4b85-8173-91819fe5f4a3.png)

Будет намного лучше, если будут выпадать только актуальные вакансии. 

Также предлагаю продумать поиск вакансий. В некоторых компаниях много разных вакансий, и искать подходящую вручную (даже среди актуальных) им будет не сильно удобно. Намного лучше, если можно будет начать вводить название вакансии, и в выпадающем списке будут отображаться только не вакансии, которые соответствуют запросу (например, вводишь C++, и появляются только те вакансии, в названии которых присутствует C++, а рекрутер уже из них выбирает ту, которая его интересует, и назначает на неё кандидата)

**Comment by haiodo** [comment]
Duplicate of #858
