### ISSUE TITLE
Не получается удалить один статус

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#872]
Не получается удалить статус "отложено":
![Снимок экрана 2022-01-25 в 17 23 34](https://user-images.githubusercontent.com/22656886/150959202-f2d614c3-2954-4c15-ad43-76114d794a31.png)

Софт говорит, что на нём есть объекты, но это не так:
![Снимок экрана 2022-01-25 в 17 23 52](https://user-images.githubusercontent.com/22656886/150959244-d68b1add-f325-49a8-8304-a3953183a7fa.png)

**Comment by BykhovDenis** [comment]
![изображение](https://user-images.githubusercontent.com/80476319/151103895-ab745afd-5bd8-4df0-ba12-9266a67c83f6.png)
В канбан представлении не отображаются аппликанты имеющие done статус, чтобы избежать излишнего засорения экрана, но их можно увидеть используя другие варианты отображения

**Comment by omkoneva** [comment]
Разобралась, вопрос снят :) Спасибо!
