### ISSUE TITLE
Ссылка на кандидата

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#877]
Исторически сложилось, что когда мы (HR) согласуем собеседование с кем-то из инженеров, мы отправляем ссылку на карточку кандидата в Trello. Эту же ссылку мы добавляем в описание события в календаре, когда создаём встречу в гугле. Её также зачастую отправляем после собеседования, когда напоминаем собеседующим о том, что нужно написать отзыв, и т.п. 

В общем, возможность отправить ссылку на кандидата - полезная и нужная фича, которой мы постоянно пользуемся :) 

Сейчас возможности отправить ссылку на кандидата из Платформы нет, поэтому мы продолжаем отправлять ссылки из Trello, а хочется уже уходить с неё и работать полноценно в Платформе.

**Comment by BykhovDenis** [comment]
#649

**Comment by omkoneva** [comment]
О, супер, что уже есть это в планах! Спасибо

**Comment by haiodo** [comment]
Fixed.
