### ISSUE TITLE
Markdown не работает

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#923]
Удобно, что в трелло (и не только) можно поставить "# ", и текст после решётки станет большим как в заголовке. Что можно сделать удобное форматирование, буллиты и прочее для более лёгкого восприятия текста. Иногда этим пользуемся. 

В Платформе этого пока нет)

**Comment by haiodo** [comment]
Нужно ввести # или ## а затем нажать Tab. Для булетов * а затем таб, Новый булет через Shift + enter.

**Comment by omkoneva** [comment]
О, спасибо! Сразу не разобралась, сорри :)

**Comment by EgorBlagov** [comment]
Заранее накидываю маркдаун в редакторе, копирую в коммент вижу вот это:

![image](https://user-images.githubusercontent.com/35273613/152501969-8e5c864c-aaec-4fe7-b413-35df72ae5a55.png)
![image](https://user-images.githubusercontent.com/35273613/152502031-74b70a48-2f57-4577-9004-22d460c857c6.png)

inline код распарсился ок но в итоге при редактировании обратно он не возвращается, обычно напишешь так:

```
вот какой-то текст и `фрагмент кода` и дальше текст
```

При редактировании комментария я могу открыть и поправить форматирование, здесь же что уже конвертировалось обратно при редактировании не возвращается

**Comment by EgorBlagov** [comment]
Inline код обычно выглядит иначе, может стоит поправить стили `чуть-чуть`
