### ISSUE TITLE
Возможность выделить все сообщения при интеграции с телеграмом

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#931]
Представляю её в верхнем правом углу (обозначила на скриншоте красным кружочком):

![Снимок экрана 2022-02-04 в 13 31 13](https://user-images.githubusercontent.com/22656886/152483574-d32e03a8-c309-45f0-9f53-5be795515fa4.png)

Чтобы была возможность либо быстро импортировать все сообщения, либо - сохранить выбранные сообщения (как сейчас)

**Comment by haiodo** [comment]
Так как сообщения доступны всем, но не сильно актуально.
