### ISSUE TITLE
Загружать резюме и в карточку кандидата, и в аппликейшен

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#947]
На примере одного кандидата обсудили следующее:
- с самой доски читаем комменты, но полностью их прочитать не получается, поэтому открываем карточку кандидата
- там есть резюме, но комментов в самой карточке нет, так как они в аппликейшене
- заходим в аппликейшен - там есть комменты, но нет резюме

То есть выпадаем из контекста каждый заход. Думаю, то резюме можно загружать и в карточку, и в аппликейшен, чтобы такого не было

**Comment by haiodo** [comment]
обсудили, текущий подход устраивает.
