### ISSUE TITLE
Переименовать некоторые названия

### ISSUE THREAD

**Issue by omkoneva** [hcengineering/platform#949]
1. Обсудили с тимлидами, что более корректно, если "application" переименовать в "case". Я привыкла к названию "application", но для тех, кто только начинает пользоваться Платформой, скорее всего "case" будет действительно звучать более логично и понятно 
2. Уже некоторое время думаю, что будет более корректно, если финальный статус "отказали" мы переименуем в "отложено" или "отклонено", так как не всегда мы кандидату отказываем. Иногда кандидат не готов рассматривать вакансии. Иногда - принимает другой оффер. Иногда просто не отвечает. И так на любом этапе может быть

Оба момента некритичные, но скорее всего новые названия будут звучать более логично и не будут вызывать у новых пользователей диссонанса

**Comment by BykhovDenis** [comment]
![изображение](https://user-images.githubusercontent.com/80476319/152788712-51d6b6dc-a30f-44b9-8b68-70883ae796c6.png)
![изображение](https://user-images.githubusercontent.com/80476319/152788814-ae4fd0ea-65c0-4e46-ac7a-0abf64e66192.png)
Статус можно переименовать в настройках статусов у вакансии, а так же в настройках для шаблона будущих вакансий.

**Comment by omkoneva** [comment]
@BykhovDenis исправила, спасибо большое :)
